var Card = {
	//CREATURE N
	C101:{id:"C101",type:"C",name:"ファイター",		cost:40, color:1,st:40,lf:40,opt:["@PROTECTION@!CLN"],imgsrc:"fighter.png",ani:"slash1",com:"無効[無]"},
	C102:{id:"C102",type:"C",name:"オーク",			cost:50, color:1,st:50,lf:50,opt:["@SLOW@"],imgsrc:"orc.png",ani:"slash1",com:"後手"},
	C103:{id:"C103",type:"C",name:"Ｇ・レイブン",	cost:40, color:1,st:20,lf:20,opt:["@FLYING@"],imgsrc:"gcrow",ani:"slash3",com:"飛行"},
	C104:{id:"C104",type:"C",name:"タワー",			cost:60, color:1,st:0, lf:40,item:"W",walk:"TI",opt:["@DEFBASE@","@LEVELUP@=150"],imgsrc:"tower.png",ani:"ball",com:"防衛：◆改築(150G)この領地のレベルを1上昇させる"},
	C105:{id:"C105",type:"C",name:"ニンジャ",		cost:80, color:1,st:40,lf:40,opt:["@FIRST@","@POISON@"],imgsrc:"ninja.png",ani:"slash1",com:"先制：猛毒"},
	C106:{id:"C106",type:"C",name:"スケルトン",		cost:40, color:1,st:20,lf:40,opt:["@REGENE@"],imgsrc:"skelton",com:"再生"},
	C107:{id:"C107",type:"C",name:"アルケミスト",	cost:50, color:1,st:30,lf:30,item:"W",opt:["@ALCHEMY@=60"],imgsrc:"alchemist.png",com:"◆錬金(60G)最後に使われたスペルを手札に追加する"},
	C108:{id:"C108",type:"C",name:"ラットヒーロー",	cost:50, color:1,st:20,lf:20,opt:["@FIRST@","@WEAPON@","@ESCAPE@"],imgsrc:"rathero.png",ani:"slash1",com:"先制：強打[武具使用時]：逃走"},
	C109:{id:"C109",type:"C",name:"クロム・Ｅ",		cost:60, color:1,st:0, lf:20,item:"W",walk:"T",opt:["@MAPDMGREDUCE@"],imgsrc:"elementalc.png",ani:"ball",com:"結界(スペルと領地能力によるダメージが10減少する)"},
	C110:{id:"C110",type:"C",name:"シーフ",			cost:60, color:1,st:30,lf:30,opt:["@STEAL@","@SPY@"],imgsrc:"thief.png",ani:"slash1",com:"察知：◇奪取"},
	C111:{id:"C111",type:"C",name:"ジャックランタン",cost:50, color:1,st:0, lf:30,opt:["@SWAP@"],imgsrc:"jolantan.png",ani:"ball",com:"戦闘終了時相手のＳＴとＭＨＰを入れ替える"},
	C112:{id:"C112",type:"C",name:"ドラゴンゾンビ",	cost:100,color:1,st:30,lf:30,opt:["@SHOOT@","@STPLUSNO@:20","@LFPLUSNO@:20"],imgsrc:"dragonzombie.png",ani:"ball",com:"射撃：戦闘時ＳＴ＆ＨＰ＋20[アイテムを使用しない場合]"},
	C113:{id:"C113",type:"C",name:"トランプガード",	cost:70, color:1,st:20,lf:20,item:"W",opt:["@AID@"],imgsrc:"trumpguard.png",ani:"slash1",com:"加勢"},
	C114:{id:"C114",type:"C",name:"マーブル・Ｅ",	cost:60, color:1,st:0, lf:20,item:"W",walk:"T",opt:["@MAPUNIQUE@"],imgsrc:"elementalm.png",ani:"ball",com:"結界(すでに配置されているクリーチャーと同名のクリーチャーは召還不可となる)"},
	C115:{id:"C115",type:"C",name:"Ｓ・ウォーカー",	cost:70, color:1,st:0, lf:30,opt:["@STEQUAL@:ENCLR10"],imgsrc:"shadowwalker.png",com:"戦闘時ＳＴ＝(マップ上対戦相手の属性クリーチャー×10)"},
	//F
	C201:{id:"C201",type:"C",name:"ミノタウロス",	cost:60, color:2,st:30,lf:40,opt:["@SMASH@"],imgsrc:"minotaur.png",ani:"slash1",com:"強打"},
	C202:{id:"C202",type:"C",name:"スパークビー",	cost:70, color:2,st:20,lf:20,opt:["@FLYING@", "@STPLUS@:BEE"],imgsrc:"sparkbee",ani:"ball",com:"飛行：戦闘時ＳＴ＋(マップ上の「スパークビー」「スカウトビー」×10)"},
	C203:{id:"C203",type:"C",name:"ケルベロス",		cost:80, color:2,st:50,lf:30,opt:["@FIRST@"],imgsrc:"cerberus",ani:"bite",com:"先制"},
	C204:{id:"C204",type:"C",name:"パイロマンサー",	cost:70, color:2,st:30,lf:30,walk:"W",opt:["@DIRECT@", "@FIREBALL@=70"],imgsrc:"piromancer.png",ani:"ball",com:"貫通：◆火球(70G)対象領地に20ダメージ：使用クリーチャーに20ダメージ"},
	C205:{id:"C205",type:"C",name:"ファイア・Ｅ",	cost:60, plus:"F", color:2,st:0, lf:20,item:"W",walk:"T",opt:["@MAPBTSTPLUS@:20"],imgsrc:"elementalf.png",ani:"ball",com:"結界(戦闘時攻撃側ＳＴ＋20)"},
	C206:{id:"C206",type:"C",name:"ドワーフ",		cost:70, color:2,st:30,lf:30,opt:["@HALFSHIELD@"],imgsrc:"dwarf",ani:"slash1",com:"頑健(戦闘時相手から受けるダメージを半減する)"},
	C207:{id:"C207",type:"C",name:"キマイラ",		cost:70, color:2,st:40,lf:40,opt:["@STEQUAL@:4CLR","@LFEQUAL@:4CLR"],imgsrc:"chimera",ani:"slash3",com:"戦闘時ＳＴ＆ＨＰ＝(相手の領地種類[火水地風]×20)"},
	C208:{id:"C208",type:"C",name:"ファイアウォール",cost:60, color:2,st:0,lf:50,item:"W",walk:"TI",opt:["@WALL@"],imgsrc:"wallf",ani:"ball",com:"拠点"},
	C209:{id:"C209",type:"C",name:"イフリート",		cost:80, color:2,st:30,lf:40,item:"W",opt:["@STEQUAL@:IFRIT"],imgsrc:"ifrit.png",ani:"ball",com:"戦闘時ＳＴ＝(支配領地[火]×20)(最大100：最低0)"},
	C210:{id:"C210",type:"C",name:"レッドドラゴン",	cost:120,plus:"F", color:2,st:50,lf:50,opt:["@FLYING@","@LEGEND@"],imgsrc:"reddragon.png",ani:"slash3",com:"飛行：召還制限(土地レベル2以上)"},
	C211:{id:"C211",type:"C",name:"ジャガーノート",	cost:70, color:2,st:40,lf:50,walk:"W",opt:["@SLOW@","@PUSH@=80"],imgsrc:"juggernaut.png",ani:"ball",com:"後手：◆押出(80G)対象の隣接するクリーチャーを直線上が空き地に移動させる"},
	C212:{id:"C212",type:"C",name:"フェニックス",		cost:60, plus:"F", color:2,st:30,lf:30,item:"I",opt:["@FLYING@","@FENIX@=100"],imgsrc:"fenix.png",ani:"slash3",com:"飛行：◆転生(100G)配置領地は売却後火属性土地になりデッキ復帰"},
	C213:{id:"C213",type:"C",name:"バーサーカー",		cost:70, color:2,st:40,lf:40,opt:["@IRONHEART@!ATK"],imgsrc:"berserker.png",ani:"slash1",com:"侵略戦闘時攻撃によりＨＰは0にならない"},
	C214:{id:"C214",type:"C",name:"マンティコア",		cost:80, plus:"F",color:2,st:40,lf:40,opt:["@POISON@","@UNTIELEMENT@=40"],imgsrc:"manticore.png",ani:"slash3",com:"猛毒：◆無地(40G)対象クリーチャーは「無地」呪いとなる。"},
	C215:{id:"C215",type:"C",name:"ケットシー",		cost:80, color:2,st:30,lf:30,opt:["@PROTECTION@!FLY","@PROTECT@"],imgsrc:"caitsith.png",ani:"slash3",com:"無効[飛行]：保護"},
	C216:{id:"C216",type:"C",name:"ボガート",			cost:60, color:2,st:10,lf:30,opt:["@GREED@","@PHANTASM@"],imgsrc:"boggart.png",ani:"ball",com:"強欲(通行料×2.0)：幻影(マップＨＰ固定)"},
	C217:{id:"C217",type:"C",name:"ウォーロード",		cost:70, color:2,st:10,lf:30,opt:["@MAPBTLFPLUSN@:20"],imgsrc:"warlord.png",ani:"slash1",com:"結界(戦闘時ＨＰ＋20[無])"},
	C218:{id:"C218",type:"C",name:"バンディクート",	cost:70, plus:"F", color:2,st:30,lf:40,opt:["@FIRST@","@REWARD@"],imgsrc:"bandicoot.png",ani:"slash3",com:"先制：侵略成功時土地レベルを１上昇させる"},
	//W
	C301:{id:"C301",type:"C",name:"マーフォーク",		cost:70, color:3,st:20,lf:30,item:"I",opt:["@BAND@"],imgsrc:"merfork",ani:"slash3",com:"援護"},
	C302:{id:"C302",type:"C",name:"クラーケン",		cost:80, color:3,st:20,lf:50,walk:"F",item:"I",opt:["@REGENE@!TEW","@DICE1@"],imgsrc:"kraken",ani:"slash3",com:"再生[水領地]：戦闘終了時、相手に「ドゥームダイス１」呪いを付加"},
	C303:{id:"C303",type:"C",name:"リヴァイアサン",	cost:120,plus:"W",color:3,st:30,lf:50,opt:["@DIRECT@!CLED","@SMASH@!CLF","@SINK@"],imgsrc:"rivaisan",ani:"bite",com:"貫通[地風]：強打[火]：侵略成功時土地属性を水属性に変化させる"},
	C304:{id:"C304",type:"C",name:"ラミア",			cost:60, color:3,st:30,lf:30,opt:["@DIVING@=20","@SPY@"],imgsrc:"lamia",ani:"slash3",com:"察知：◆潜水(20G)対象の水属性土地(空地)に移動"},
	C305:{id:"C305",type:"C",name:"バルーンアメーバ",	cost:50, color:3,st:10,lf:10,opt:["@FLYING@","@BALOON@"],imgsrc:"baloon",ani:"ball",com:"飛行：◇膨張(プレイヤーが通過する度にＭＨＰ＋10、ＭＨＰが100以上になると破壊される)"},
	C306:{id:"C306",type:"C",name:"ウォーター・Ｅ",	cost:60, plus:"W",color:3,st:0, lf:20,item:"W",walk:"T",opt:["@MAPBTINVALID@:30"],imgsrc:"elementalw.png",ani:"ball",com:"結界(戦闘時基本ＳＴ30以下はＳＴ＝0)"},
	C307:{id:"C307",type:"C",name:"アイスウォール",	cost:60, color:3,st:0, lf:50,item:"W",walk:"TI",opt:["@WALL@"],imgsrc:"wallw",ani:"ball",com:"拠点"},
	C308:{id:"C308",type:"C",name:"ネクロマンサー",	cost:60, color:3,st:30,lf:30,opt:["@RITUAL@=80"],imgsrc:"necromancer",ani:"ball",com:"◆召喚(80G)マップ上のランダムな空き地にスケルトンを召喚する"},
	C309:{id:"C309",type:"C",name:"ケルピー",			cost:70, color:3,st:20,lf:40,item:"W",opt:["@QUICKSAND@=100"],imgsrc:"kelpie.png",ani:"slash3",com:"◆足止(100G)この領地を「足止」呪いにする"},
	C310:{id:"C310",type:"C",name:"リザードマン",		cost:70, color:3,st:30,lf:40,opt:["@FIRST@","@SHOOT@"],imgsrc:"rizardman.png",ani:"slash1",com:"先制：射撃"},
	C311:{id:"C311",type:"C",name:"Ｓ・スライム",		cost:40, color:3,st:20,lf:20,walk:"FD",opt:["@HALFSHIELD@","@STICKY@"],imgsrc:"stickyslime.png",ani:"ball",com:"頑健：戦闘破壊時手札に「Ｓ・スライム」を2枚得る"},
	C312:{id:"C312",type:"C",name:"メデューサ",		cost:70, color:3,st:30,lf:30,opt:["@STONE@","@PROTECTION@!CLN"],imgsrc:"medusa.png",ani:"slash3",com:"即死[無]：無効[無]"},
	C313:{id:"C313",type:"C",name:"ウィザード",		cost:70, color:3,st:0, lf:30,item:"W",opt:["@CURSEDMG@:30","@DRAWCARD@=40"],imgsrc:"wizard.png",ani:"ball",com:"呪術(戦闘終了時相手に30ダメージ)：◆補充(40G)カードを1枚引く"},
	C314:{id:"C314",type:"C",name:"パイレーツ",		cost:80, color:3,st:30,lf:20,walk:"ED",opt:["@BAND@","@DIRECT@!CLFW"],imgsrc:"pirate.png",ani:"slash1",com:"援護：貫通[火水]"},
	C315:{id:"C315",type:"C",name:"バンシー",			cost:70, color:3,st:20,lf:30,walk:"I",opt:["@FORGET@","@DISPEL@=60"],imgsrc:"bansee.png",ani:"slash3",com:"忘却：◆絶叫(60G)プレイヤー全員の呪いが消える"},
	C316:{id:"C316",type:"C",name:"ブラックナイト",	cost:70, color:3,st:40,lf:40,opt:["@HUNTER@"],imgsrc:"blackknight.png",ani:"slash1",com:"攻撃成功時武具を使用していた場合ダメージ分のGを奪う"},
	C317:{id:"C317",type:"C",name:"ノーチラス",		cost:50, color:3,st:40,lf:30,opt:["@STPLUS@:10!CURSED","@LFPLUS@:10!CURSED"],imgsrc:"nautilus.png",ani:"ball",com:"戦闘時ＳＴ＆ＨＰ＋10[呪いがかかっている領地]"},
	//E
	C401:{id:"C401",type:"C",name:"Ｇ・フロッグ",		cost:60, color:4,st:30,lf:40,opt:["@POISON@","@SHOOT@"],imgsrc:"gflog",ani:"slash3",com:"猛毒：射撃"},
	C402:{id:"C402",type:"C",name:"ガーゴイル",		cost:70, color:4,st:40,lf:40,walk:"T",opt:["@DEFBASE@"],imgsrc:"gargoyle",ani:"slash3",com:"防衛"},
	C403:{id:"C403",type:"C",name:"ケンタウロス",		cost:90, color:4,st:30,lf:30,opt:["@BAND@","@SHOOT@"],imgsrc:"centaur.png",ani:"slash1",com:"援護：射撃"},
	C404:{id:"C404",type:"C",name:"ロックイーター",	cost:70, color:4,st:30,lf:30,item:"W",opt:["@LFEQUAL@:TE20"],imgsrc:"rockeater",ani:"bite",com:"戦闘時ＨＰ＝(所有地属性領地×20)"},
	C405:{id:"C405",type:"C",name:"アース・Ｅ",		cost:60 ,plus:"E",color:4,st:0, lf:20,item:"W",walk:"T",opt:["@MAPTERRITORYLOCK@"],imgsrc:"elementale.png",ani:"ball",com:"結界(領地移動不可)"},
	C406:{id:"C406",type:"C",name:"サスカッチ",		cost:110,color:4,st:60,lf:60,item:"WI",imgsrc:"fgiant",ani:"slash3"},
	C407:{id:"C407",type:"C",name:"ストーンウォール",	cost:60, color:4,st:0,lf:50,item:"W",walk:"TI",opt:["@WALL@"],imgsrc:"walle",ani:"ball",com:"拠点"},
	C408:{id:"C408",type:"C",name:"ドリアード",		cost:80, color:4,st:20,lf:30,item:"W",opt:["@BAND@","@PROTECT@"],imgsrc:"driard.png",ani:"slash3",com:"援護：保護"},
	C409:{id:"C409",type:"C",name:"バジリスク",		cost:70, color:4,st:40,lf:40,opt:["@DEATH@"],imgsrc:"basilisk.png",ani:"bite",com:"即死(アイテム不使用時に相手が使用時)"},
	C410:{id:"C410",type:"C",name:"ドルイド",			cost:70, color:4,st:30,lf:30,opt:["@RUST@=60"],imgsrc:"druid.png",ani:"ball",com:"◆破砕(60G)相手プレイヤー全員の手札からアイテム[武具]をランダムに1枚破壊する"},
	C411:{id:"C411",type:"C",name:"エルフレンジャー",	cost:60, color:4,st:30,lf:30,opt:["@SCOUT@","@SPY@"],imgsrc:"elvenranger.png",ani:"slash1",com:"察知：◇偵察(所有者通過時呪い状態でなければ「啓示」呪い(1ターン)となる)"},
	C412:{id:"C412",type:"C",name:"カーバンクル",		cost:70, color:4,st:20,lf:20,opt:["@BAND@","@REFLECT@"],imgsrc:"carbuncle.png",ani:"slash3",com:"援護：反射"},
	C413:{id:"C413",type:"C",name:"フォレストマザー",	cost:100,plus:"E",color:4,st:20,lf:40,walk:"TI",opt:["@LFPLUS@:20!TEE","@WALL@","@PHANTASM@"],imgsrc:"fmother.png",ani:"ball",com:"戦闘時ＨＰ＋20[地領地]：拠点：幻影(マップＨＰ固定)"},
	C414:{id:"C414",type:"C",name:"タイタン",			cost:100,plus:"E",color:4,st:50,lf:50,opt:["@SMASH@!LF50"],imgsrc:"titan.png",ani:"ball",com:"強打[MAXHP50以上]"},
	C415:{id:"C415",type:"C",name:"ファンガス",		cost:70, color:4,st:20,lf:30,opt:["@POISON@","@DIVISION@=40"],imgsrc:"fangus.png",ani:"ball",com:"猛毒：◆分裂(40G)"},
	C416:{id:"C416",type:"C",name:"エルフメイジ",		cost:60, plus:"E",color:4,st:30,lf:30,opt:["@ADAPTATION@"],imgsrc:"elvenlord.png",ani:"ball",com:"戦闘開始時条件を満たした分だけ能力を付加、先制[戦闘領地が地属性]、呪術[支配領地に隣接]、頑健[城砦に隣接]"},
	C417:{id:"C417",type:"C",name:"マスターパンダ",	cost:60, color:4,st:30,lf:40,item:"I",opt:["@COUNTER@"],imgsrc:"masterpanda.png",ani:"ball",com:"戦闘時攻撃ダメージを受けた後にＨＰが1以上あれば受けたダメージを相手に与える"},
	//D
	C501:{id:"C501",type:"C",name:"グリフォン",		cost:90, color:5,st:40,lf:30,opt:["@FLYING@"],imgsrc:"gliffin",ani:"slash3",com:"飛行"},
	C502:{id:"C502",type:"C",name:"ペガサス",			cost:80, color:5,st:30,lf:20,opt:["@FLYING@","@GLIDE@=60"],imgsrc:"pegasus",ani:"slash3",com:"飛行：◆滑空(60G)対象のレベル１の土地に移動"},
	C503:{id:"C503",type:"C",name:"ナイト",			cost:70, color:5,st:40,lf:40,opt:["@WEAPON@"],imgsrc:"knight.png",ani:"slash1",com:"強打[武具使用時]"},
	C504:{id:"C504",type:"C",name:"スフィンクス",		cost:70, color:5,st:20,lf:50,opt:["@FIRST@","@SPHINX@"],imgsrc:"sphinx",ani:"slash3",com:"先制：戦闘時ラウンド数が奇数ならＳＴ＋30＆ＨＰ－30、10の倍数ならＳＴ＋30"},
	C505:{id:"C505",type:"C",name:"サンドゴーレム",	cost:80, color:5,st:60,lf:60,opt:["@LFPLUS@:RDEC","@STPLUS@:RDEC"],imgsrc:"sgolem",ani:"slash3",com:"戦闘時ＳＴ＆ＨＰ－(ラウンド数)"},
	C506:{id:"C506",type:"C",name:"エア・Ｅ",			cost:60, plus:"D", color:5,st:0, lf:20,item:"W",walk:"T",opt:["@MAPBTFLYING@"],imgsrc:"elementala.png",ani:"ball",com:"結界(戦闘時飛行はＳＴ＆ＨＰ＋10)"},
	C507:{id:"C507",type:"C",name:"ウィッチ",			cost:60, color:5,st:0,lf:30,item:"W",opt:["@CURSEDMG@:30","@DRAIN@=30"],imgsrc:"witch",ani:"ball",com:"呪術(戦闘終了時相手に30ダメージ)：◆吸収(30G)対象プレイヤーの所持魔力の20%を奪う"},
	C508:{id:"C508",type:"C",name:"サンドウォール",	cost:60, color:5,st:0,lf:50,item:"W",walk:"TI",opt:["@WALL@"],imgsrc:"walld",ani:"ball",com:"拠点"},
	C509:{id:"C509",type:"C",name:"アークエンジェル",	cost:110,plus:"D",color:5,st:40,lf:40,item:"W",opt:["@FLYING@","@CLEAR@","@REMOVE@=40"],imgsrc:"archangelus.png",ani:"ball",com:"飛行：浄化：◆解呪(40G)対象領地の呪いを解除する"},
	C510:{id:"C510",type:"C",name:"ナイトメア",		cost:60, color:5,st:30,lf:30,opt:["@NIGHTMARE@"],imgsrc:"nightmare.png",ani:"ball",com:"周回ボーナス時ラウンド数をチェックする(奇数)ＳＴ＆ＨＰ＋10(最大70)：(偶数)隣接する空き地全てに自身をコピーする"},
	C511:{id:"C511",type:"C",name:"ハーピー",			cost:80, color:5,st:20,lf:30,walk:"E",opt:["@FLYING@","@BIND@"],imgsrc:"harpy.png",ani:"slash3",com:"飛行：麻痺"},
	C512:{id:"C512",type:"C",name:"キュウビ",			cost:70, plus:"D",color:5,st:30,lf:40,walk:"TI",opt:["@WALL@","@PROTECT@"],imgsrc:"ninetail.png",ani:"slash3",com:"拠点：保護"},
	C513:{id:"C513",type:"C",name:"グレムリン",		cost:60, color:5,st:30,lf:40,opt:["@DISCARD@"],imgsrc:"gremlin.png",ani:"slash3",com:"戦闘時攻撃成功した場合(ダメージが1以上)相手プレイヤーはランダムに手札を1枚破棄"},
	C514:{id:"C514",type:"C",name:"スカウトビー",		cost:70, color:5,st:20,lf:20,opt:["@FLYING@","@SPY@","@TOUR@=20"],imgsrc:"scoutbee.png",ani:"slash3",com:"飛行：察知：◆巡回(20G)対象の風属性土地(空地)に移動"},
	C515:{id:"C515",type:"C",name:"デュラハン",		cost:70, plus:"D",color:5,st:0,lf:40,opt:["@STEQUAL@:CN10","@LFEQUAL@:CN10"],imgsrc:"dullahan.png",ani:"slash1",com:"戦闘時ＳＴ＆ＨＰ＝(マップ上の無属性クリーチャー×10)"},
	C516:{id:"C516",type:"C",name:"ウロボロス",		cost:90, color:5,st:40,lf:30,item:"I",opt:["@UROBOROS@"],imgsrc:"uroboros.png",ani:"bite",com:"戦闘破壊時領地数が最低の場合再召喚される"},
	C517:{id:"C517",type:"C",name:"ムシュフシュ",		cost:80, color:5,st:40,lf:40,walk:"E",opt:["@POISON@", "@DIRECT@!POISON"],imgsrc:"musus.png",ani:"bite",com:"猛毒：貫通[猛毒呪い]"},
	//ITEM
	I001:{id:"I001",type:"I",name:"ロングソード",		cost:40,item:"W",opt:["STPLUS:40"],imgsrc:"longsword",com:"ＳＴを40上昇させる"},
	I002:{id:"I002",type:"I",name:"プレートメイル",	cost:40,item:"W",opt:["LFPLUS:40"],imgsrc:"platemail",com:"ＨＰを40上昇させる"},
	I003:{id:"I003",type:"I",name:"ロングボウ",		cost:60,item:"W",opt:["STPLUS:20","FIRST","SHOOT"],imgsrc:"longbow.png",com:"ＳＴを20上昇させる：先制：射撃"},
	I004:{id:"I004",type:"I",name:"スレッジハンマー",	cost:60,item:"W",opt:["STPLUS:30","SMASH","SLOW"],imgsrc:"sledge.png",com:"ＳＴを30上昇させる：強打：後手"},
	I005:{id:"I005",type:"I",name:"アイアンハート",	cost:70,item:"I",opt:["IRONHEART"],imgsrc:"ironheart.png",com:"ＨＰを超えるダメージを受けた場合、ＨＰ＝1[はじめからＨＰ＝1の時は軽減できない]"},
	I006:{id:"I006",type:"I",name:"ホーリーストーン",	cost:100,item:"I",opt:["HOLYSTONE"],imgsrc:"holystone",com:"戦闘開始時相手の援護クリーチャー・アイテムカードを破壊する"},
	I007:{id:"I007",type:"I",name:"アサシンクローク",	cost:40,item:"I",opt:["STPLUS:40!NOITEM","LFPLUS:40!NOITEM"],imgsrc:"assassin",com:"相手がアイテムカード未使用時、ＳＴ＆ＨＰを40上昇させる"},
	I008:{id:"I008",type:"I",name:"イビルストーン",	cost:60,item:"I",opt:["EVILSTONE"],imgsrc:"evilstone",com:"戦闘時相手クリーチャーの能力が発生しなくなる"},
	I009:{id:"I009",type:"I",name:"ディバイン・Ｓ",	cost:60,item:"I",opt:["DIVINESTONE"],imgsrc:"divinestone",com:"ダメージを1/2跳ね返す"},
	I010:{id:"I010",type:"I",name:"バックラー",		cost:40,item:"W",opt:["LFPLUS:20","STMINUS:20","BACKHAND"],imgsrc:"buckler.png",com:"ＳＴ－20：ＨＰ＋20：手札復帰"},
	I011:{id:"I011",type:"I",name:"スピア",			cost:60,item:"W",opt:["LFPLUS:20","STPLUS:20","SHOOT"],imgsrc:"spear.png",com:"ＳＴ＋20：ＨＰ＋20：射撃"},
	I012:{id:"I012",type:"I",name:"コールドストーン",	cost:40,item:"I",opt:["STEQUAL:50","LFEQUAL:50"],imgsrc:"coldstone.png",com:"ＳＴ＝50：ＨＰ＝50"},
	I013:{id:"I013",type:"I",name:"フェザークラウン",	cost:40,item:"I",opt:["FIRST","BACKHAND"],imgsrc:"feathercrown.png",com:"先制：手札復帰"},
	I014:{id:"I014",type:"I",name:"オオダチ",			cost:80,item:"W",opt:["STPLUS:HANDM80"],imgsrc:"ootachi.png",com:"ＳＴ＋80－(自分の手札枚数×10)"},
	I015:{id:"I015",type:"I",name:"ブラックスワン",	cost:0, item:"I",opt:["BLACKSWAN"],imgsrc:"blackswan.png",com:"戦闘終了時対戦相手が生存していればHP×10Gを得る"},
	I016:{id:"I016",type:"I",name:"レイピア",			cost:30,item:"W",opt:["STPLUS:30","REVDEATH"],imgsrc:"rapier.png",com:"ＳＴを30上昇させる：雪辱[即死]"},
	I017:{id:"I017",type:"I",name:"イージス",			cost:60,item:"W",opt:["LFPLUS:20","AEGIS"],imgsrc:"aegis.png",com:"ＨＰ＋20：無効[相手が武具使用時]"},
	//SPELL
	S001:{id:"S001",type:"S",name:"マナ",				cost:0,  spell:"MANA",		tgt:"AMP",imgsrc:"mana",com:"周回数×50Gを得る"},
	S002:{id:"S002",type:"S",name:"ドゥームダイス１",	cost:30, spell:"SETSTATUSP",tgt:"TEP",opt:["_DICE_:1","1"],imgsrc:"magicdice1.png",com:"(呪い1ターン)対象プレイヤーのダイスは1になる"},
	S003:{id:"S003",type:"S",name:"ドゥームダイス７",	cost:60, spell:"SETSTATUSP",tgt:"TEP",opt:["_DICE_:7","1"],imgsrc:"magicdice7.png",com:"(呪い1ターン)対象プレイヤーのダイスは7になる"},
	S004:{id:"S004",type:"S",name:"ホープ",			cost:40, spell:"DRAW",		tgt:"AMP",opt:["2"],imgsrc:"hope",com:"カードを2枚引く"},
	S005:{id:"S005",type:"S",name:"ヒール",			cost:30, spell:"HEAL",		tgt:"TEGALL",imgsrc:"heal",com:"対象クリーチャーのHPを全回復し、全ての呪いを解除する：デッキ復帰"},
	S006:{id:"S006",type:"S",name:"シャッター",		cost:60, spell:"SHUTTER",	tgt:"TOP",imgsrc:"shatter.png",com:"対象プレイヤーのアイテムカード、スペルカードの内1枚を選択して破壊する"},
	S007:{id:"S007",type:"S",name:"アップヒーバル",	cost:150,spell:"COLORCHANGE",tgt:"TEG",opt:["2"],imgsrc:"colorf",com:"対象の領地を火属性に変える"},
	S008:{id:"S008",type:"S",name:"シンク",			cost:150,spell:"COLORCHANGE",tgt:"TEG",opt:["3"],imgsrc:"colorw",com:"対象の領地を水属性に変える"},
	S009:{id:"S009",type:"S",name:"ワイルドグロース",	cost:150,spell:"COLORCHANGE",tgt:"TEG",opt:["4"],imgsrc:"colore",com:"対象の領地を地属性に変える"},
	S010:{id:"S010",type:"S",name:"ウェザリング",		cost:150,spell:"COLORCHANGE",tgt:"TEG",opt:["5"],imgsrc:"colord",com:"対象の領地を風属性に変える"},
	S011:{id:"S011",type:"S",name:"リンカネーション",	cost:40, spell:"REINCARNE"	,tgt:"AMP",imgsrc:"reincarne",com:"手札を全て破棄して、破棄枚数+1枚を引く"},
	S012:{id:"S012",type:"S",name:"マジックボルト",	cost:60, spell:"DAMAGE",	tgt:"TOG",opt:["20"],imgsrc:"magicbolt",com:"対象クリーチャーに20ダメージ"},
	S013:{id:"S013",type:"S",name:"バンク",			cost:0,  spell:"SETSTATUSP",tgt:"AMP",opt:["_BANK_:250", "2"],imgsrc:"bank",com:"(呪い2ターン)2ターン後に250Gを得る"},
	S014:{id:"S014",type:"S",name:"インスペクション",	cost:40, spell:"INSPECTION",tgt:"AOP",imgsrc:"inspection",com:"相手全員からアイテムカード枚数×30Gを奪う(可能なかぎり)"},
	S015:{id:"S015",type:"S",name:"マーケット",		cost:40, spell:"MARKET",	tgt:"AOP",imgsrc:"market",com:"相手全員の手札からスペルカードを各2枚ランダムに表示し、選択したカードを取得して所有者に80G支払う"},
	S016:{id:"S016",type:"S",name:"ドレインマジック",	cost:80, spell:"DRAIN",		tgt:"TOP",opt:["30"],imgsrc:"drain",com:"対象プレイヤーの所持魔力の30%を奪う"},
	S017:{id:"S017",type:"S",name:"テレポート",		cost:40, spell:"TELEPORT",	tgt:"AMP",opt:["special"],imgsrc:"teleport",com:"一番近い特殊地形に移動する(複数存在する場合は選択)(ダイス使用不可)"},
	S018:{id:"S018",type:"S",name:"バインド",			cost:60, spell:"SETSTATUSG",tgt:"TEG",opt:["_BIND_","99"],imgsrc:"bind",com:"(呪い)対象のクリーチャーは「麻痺」呪いとなる"},
	S019:{id:"S019",type:"S",name:"フリング",			cost:50, spell:"FLING",		tgt:"TSG",imgsrc:"fling",com:"使用者が支配領地上にいる場合、配置クリーチャーを対象の空き土地に移動する：デッキ復帰"},
	S020:{id:"S020",type:"S",name:"フォージリィ",		cost:80, spell:"SETSTATUSP",tgt:"AMP",opt:["_FORGERY_","99"],imgsrc:"forgery",com:"(呪い城まで)通過砦に関わらず城到着にて周回となる：基礎ボーナス×1.5：砦ボーナスが受け取れない"},
	S021:{id:"S021",type:"S",name:"プロテクト",		cost:70, spell:"SETSTATUSG",tgt:"TEG",opt:["_PROTECT_","99"],imgsrc:"protect.png",com:"(呪い)対象の領地はスペル、領地能力の対象に選択できない"},
	S022:{id:"S022",type:"S",name:"アンサモン",		cost:140,spell:"UNSUMMON",	tgt:"TOG",opt:[],imgsrc:"unsummon",com:"対象のダメージを受けているクリーチャーを使用者の手札に戻す"},
	S023:{id:"S023",type:"S",name:"ナビゲート",		cost:50, spell:"SETSTATUSP",tgt:"AMP",opt:["_NAVIGATE_","2"],imgsrc:"navigate",com:"(呪い2ターン)ダイスの結果を二つから選択できる"},
	S024:{id:"S024",type:"S",name:"ディザスター",		cost:200,spell:"AREADMG",	tgt:"AEGMASS",opt:["20"],imgsrc:"dizaster",com:"マップ上に最も多い属性土地にいるクリーチャー全てに20ダメージ"},
	S025:{id:"S025",type:"S",name:"リコンストラクト",	cost:80 ,spell:"SETSTATUSG",tgt:"TEG",opt:["_RECONSTRUCT_","99","draw"],imgsrc:"reconstruct",com:"(呪い)対象領地上でターン終了された場合、基本土地価値が10上昇(最大200)：カードを１枚引く"},
	S026:{id:"S026",type:"S",name:"フェスティバル",	cost:0,  spell:"FESTIVAL",	tgt:"AMP",opt:["150"],imgsrc:"festival.png",com:"使用者は手札のクリーチャーカードを全て破棄し、破棄枚数×150Gを得る"},
	S027:{id:"S027",type:"S",name:"テレグノーシス",	cost:70, spell:"SETSTATUSP",tgt:"AMP",opt:["_TELEGNOSIS_", "2"],imgsrc:"telegnosis",com:"(呪い2ターン)領地コマンド時全ての自領地を選択できる"},
	S028:{id:"S028",type:"S",name:"アースクエイク",	cost:250,spell:"EARTHQUAKE",tgt:"AEGGRD",opt:[],imgsrc:"earthquake",com:"手札から「アースクエイク」を全て破棄：飛行を持たないクリーチャー全てに10＋(破棄枚数×10)ダメージ(最大30)"},
	S029:{id:"S029",type:"S",name:"フォーサイト",		cost:40, spell:"FORESIGHT",	tgt:"AMP",opt:["4"],imgsrc:"foresight",com:"デッキの上から4枚確認して選択した1枚を引く(デッキの残り枚数以上は確認できない)"},
	S030:{id:"S030",type:"S",name:"ショートカット",	cost:30, spell:"SETSTATUSP",tgt:"AMP",opt:["_SHORTCUT_:3","3"],imgsrc:"shortcut",com:"(呪い3ターン)ダイスの最大値をマップの最大値＋3"},
	S031:{id:"S031",type:"S",name:"ジェイル",			cost:80, spell:"SETSTATUSG",tgt:"TEG",opt:["_JAIL_","99"],imgsrc:"jail",com:"(呪い)対象の領地は戦闘不可となり通行料が発生しない：領地コマンド「レベルアップ」「地形変化」が行えない"},
	S032:{id:"S032",type:"S",name:"プレイグ",			cost:70, spell:"SETSTATUSP",tgt:"TEP",opt:["_PLAGUE_","2"],imgsrc:"plague",com:"(呪い2ターン)対象プレイヤーは「疫病」呪いとなる(疫病呪いのプレイヤーが通過した領地は「猛毒」呪いとなる)"},
	S033:{id:"S033",type:"S",name:"フラットライン",	cost:60, spell:"FLATLINE",	tgt:"AEP",opt:[],imgsrc:"flatline",com:"プレイヤー全員の手札は4枚となるようにデッキからドローまたは手札がランダム破棄される。"},
	S034:{id:"S034",type:"S",name:"エクスチェンジ",	cost:30, spell:"EXCHANGE",	tgt:"TMG,TOG",opt:[],imgsrc:"exchange.png",com:"対象の支配クリーチャー1体と対象の相手クリーチャー１体のＳＴを入れ替える：デッキ復帰"},
	S035:{id:"S035",type:"S",name:"バリアー",			cost:60, spell:"SETSTATUSP",tgt:"AMP",opt:["_BARRIER_","6"],imgsrc:"barrier.png",com:"(呪い4ターン)使用者は対象を取るスペル・領地能力の対象にならない"},
	S036:{id:"S036",type:"S",name:"リリーフ",			cost:30, spell:"RELIEF",	tgt:"TMG,TMG",opt:[],imgsrc:"relief.png",com:"対象の支配クリーチャーを2体選択し位置を入れ替える：デッキ復帰"},
	S037:{id:"S037",type:"S",name:"インシネレイト",	cost:70, spell:"INCINERATE",tgt:"TOG",opt:["10"],imgsrc:"incinerate.png",com:"対象クリーチャーに10＋(既に使用された「インシネレイト」の枚数×10)ダメージ(最大40)"},
	S038:{id:"S038",type:"S",name:"コンプレッション",	cost:40, spell:"COMPRESSION",tgt:"TEP",opt:[],imgsrc:"compression.png",com:"対象プレイヤーのデッキの上から5枚確認して選択したカードまで上から破棄する。"},
	S039:{id:"S039",type:"S",name:"コントラクト",		cost:120,spell:"CONTRACT",	tgt:"TEG",opt:[],imgsrc:"contract.png",com:"MHP－20：(呪い)通行料が所有者の最大通行料と同額となる"},
	S040:{id:"S040",type:"S",name:"パニッシャー",		cost:150,spell:"AREADMG",	tgt:"AEGCURSED",opt:["20"],imgsrc:"panisher.png",com:"呪い状態のクリーチャー全てに20ダメージ"},
	S041:{id:"S041",type:"S",name:"テレパシー",		cost:50, spell:"SETSTATUSG",tgt:"TEG",opt:["_TELEPATHY_","99"],imgsrc:"telepathy.png",com:"(呪い)常に領地コマンド対象となる：領地コマンド使用時呪い解除"},
	//d.push({id:"S042",type:"S",name:"リンクゲート",		cost:60, spell:"LINKGATE",	tgt:"AMG",opt:["_LINKGATE_",99],imgsrc:"linkgate.png",com:"(呪い)対象の属性色の支配領地は転送呪い(この領地に停止時支配領地なら他の転送呪いに移動可)となる"});
	S043:{id:"S043",type:"S",name:"バランス",			cost:30, spell:"BALANCE",	tgt:"AEP",opt:[],imgsrc:"balance.png",com:"全てのプレイヤーは順位×領地数×20Gを得る"},
	S044:{id:"S044",type:"S",name:"グラビティ",		cost:70, spell:"SETSTATUSG",tgt:"TEG",opt:["_GRAVITY_","99","draw"],imgsrc:"gravity.png",com:"(呪い)対象のクリーチャーは「重力」呪い(領地移動不可：戦闘時ＳＴ－10、ＨＰ＋10)となる：カードを1枚引く"},
	S045:{id:"S045",type:"S",name:"オブリビオン",		cost:40, spell:"SETSTATUSG",tgt:"TEG",opt:["_FORGET_","99"],imgsrc:"oblivion.png",com:"(呪い)対象のクリーチャーは「忘却」呪いとなる"},
	S046:{id:"S046",type:"S",name:"フラクチャー",		cost:150,spell:"FRACTURE",	tgt:"TEG",opt:[],imgsrc:"fracture.png",com:"対象の領地はレベル1にする：その後所有者のランダムな土地1つを下降したレベル分レベル上昇する"},
	S047:{id:"S047",type:"S",name:"エスケープ",		cost:20, spell:"TELEPORT",	tgt:"AMP",opt:["escape"],imgsrc:"escape.png",com:"使用者は一番近い空き地に移動する(複数存在する場合は選択)(ダイス使用不可)"},
	S048:{id:"S048",type:"S",name:"ハリケーン",		cost:120,spell:"AREASTATUS",tgt:"AEGFLY",opt:["_BIND_","2"],imgsrc:"hurricane.png",com:"(呪い2ターン)飛行を持つクリーチャーは全て「麻痺」呪いとなる"},
	S049:{id:"S049",type:"S",name:"ウォークライ",		cost:60, spell:"SETSTATUSP",tgt:"AMP",opt:["_WARCRY_","99"],imgsrc:"warcry.png",com:"(呪い)使用者は「行軍」呪いとなる(ターン開始時のドローカードを公開：クリーチャーだった場合コスト分のＧを得る)"},
	S050:{id:"S050",type:"S",name:"ソウルコレクト",	cost:10, spell:"SOULCOLECT",tgt:"AMP",opt:["40"],imgsrc:"soulcolect.png",com:"破壊クリーチャー数×40Gを得る：破壊クリーチャー数は0となる"},
	S051:{id:"S051",type:"S",name:"ギャザー",			cost:0,  spell:"SETSTATUSP",tgt:"AMP",opt:["_GATHER_","3"],imgsrc:"gather.png",com:"(呪い3ターン)対象プレイヤーは「収集」呪いとなる"},
	S052:{id:"S052",type:"S",name:"ルイン",			cost:100,spell:"RUIN",		tgt:"AEP",opt:[],imgsrc:"ruin.png",com:"プレイヤー全員の手札にあるアイテムカード[道具]を破壊する"},
	S053:{id:"S053",type:"S",name:"スワンプ",			cost:120,spell:"SETSTATUSG",tgt:"TEG",opt:["_SWAMP_","4"],imgsrc:"swamp.png",com:"(呪い4ターン)対象領地の地価は70%となる"},
	S054:{id:"S054",type:"S",name:"インフルエンス",	cost:80, spell:"INFLUENCE",	tgt:"TEG",opt:[],imgsrc:"influence.png",com:"対象の領地を所有者が最も所持している属性に変える"},
	S055:{id:"S055",type:"S",name:"ディストーション",	cost:70, spell:"DISTORTION",tgt:"TEG",opt:[],imgsrc:"distortion.png",com:"対象のクリーチャーはデッキ内のランダムなクリーチャーと交換される"},
	S056:{id:"S056",type:"S",name:"モノポリー",		cost:120,spell:"MONOPOLY",	tgt:"AMP",opt:["_MONOPOLY_","1"],imgsrc:"monopoly.png",com:"(呪い1ターン)使用者は「独占」呪いとなる(通行料を全て奪う)：他のプレイヤー「独占」呪いを解除"},
	S057:{id:"S057",type:"S",name:"スピリットウォーク",cost:20, spell:"SETSTATUSG",tgt:"TEG",opt:["_SPIRITWALK_","99"],imgsrc:"spiritwalk.png",com:"(呪い)対象のクリーチャーは「跳躍」呪いとなる"},
	S058:{id:"S058",type:"S",name:"リサーチ",			cost:40, spell:"DRAW",		tgt:"AMP",opt:["1","hand"],imgsrc:"research.png",com:"カードを1枚引く：手札復帰"},
	S059:{id:"S059",type:"S",name:"クエスト",			cost:20, spell:"QUEST",		tgt:"AMP",opt:["_QUEST_","3"],imgsrc:"quest.png",com:"(呪い3ターン)使用者は「冒険」呪いとなる(侵略成功時呪い以降の侵略成功回数×200Gを得て期間が再び3ターンとなる：最大3回)"},
	S060:{id:"S060",type:"S",name:"アップドラフト",	cost:80, spell:"AREASTATUS",tgt:"AEGHP30",opt:["_SPIRITWALK_"],imgsrc:"updraft.png",com:"(呪い)ＭＨＰが30以下のクリーチャーは「跳躍」呪いとなる"},
	//S061:{id:"S061",type:"S",name:"プライア",			cost:60, spell:"SETSTATUSP",tgt:"AMP",opt:["_PRAYER_",1],imgsrc:"testspell",com:"(呪い1ターン)使用者は「祈願」呪いとなる(土地レベルアップコストが1/2となる)"},
}
