var Card = {
	//CREATURE N
	C101:{id:"C101",ctype:"C",name:"ファイター",		cost:40, color:1,st:40,lf:40,opt1:"@PROTECTION@!CLN",imgsrc:"fighter.png",ani:"slash1",com:"無効[無]"},
	C102:{id:"C102",ctype:"C",name:"オーク",			cost:50, color:1,st:50,lf:50,opt1:"@SLOW@",imgsrc:"orc.png",ani:"slash1",com:"後手"},
	C103:{id:"C103",ctype:"C",name:"Ｇ・レイブン",		cost:40, color:1,st:20,lf:20,opt1:"@FLYING@",imgsrc:"gcrow",ani:"slash3",com:"飛行"},
	C104:{id:"C104",ctype:"C",name:"タワー",			cost:60, color:1,st:0, lf:40,item:"W",walk:"TI",opt1:"@DEFBASE@",opt2:"@LEVELUP@=150",imgsrc:"tower.png",ani:"ball",com:"防衛：◆改築(150G)この領地のレベルを1上昇させる"},
	C105:{id:"C105",ctype:"C",name:"ニンジャ",			cost:80, color:1,st:40,lf:40,opt1:"@FIRST@",opt2:"@POISON@",imgsrc:"ninja.png",ani:"slash1",com:"先制：猛毒"},
	C106:{id:"C106",ctype:"C",name:"スケルトン",		cost:40, color:1,st:20,lf:40,opt1:"@REGENE@",imgsrc:"skelton",com:"再生"},
	C107:{id:"C107",ctype:"C",name:"アルケミスト",		cost:50, color:1,st:30,lf:30,item:"W",opt1:"@ALCHEMY@=60",imgsrc:"alchemist.png",com:"◆錬金(60G)最後に使われたスペルを手札に追加する"},
	C108:{id:"C108",ctype:"C",name:"ラットヒーロー",	cost:50, color:1,st:20,lf:20,opt1:"@FIRST@",opt2:"@WEAPON@",opt3:"@ESCAPE@",imgsrc:"rathero.png",ani:"slash1",com:"先制：強打[武具使用時]：逃走"},
	C109:{id:"C109",ctype:"C",name:"クロム・Ｅ",		cost:60, color:1,st:0, lf:20,item:"W",walk:"T",opt1:"@MAPDMGREDUCE@",imgsrc:"elementalc.png",ani:"ball",com:"結界(スペルと領地能力によるダメージが10減少する)"},
	C110:{id:"C110",ctype:"C",name:"シーフ",			cost:60, color:1,st:30,lf:30,opt1:"@STEAL@",opt2:"@SPY@",imgsrc:"thief.png",ani:"slash1",com:"察知：◇奪取"},
	C111:{id:"C111",ctype:"C",name:"ジャックランタン",	cost:50, color:1,st:0, lf:30,opt1:"@SWAP@",imgsrc:"jolantan.png",ani:"ball",com:"戦闘終了時相手のＳＴとＭＨＰを入れ替える"},
	C112:{id:"C112",ctype:"C",name:"ドラゴンゾンビ",	cost:100,color:1,st:30,lf:30,opt1:"@SHOOT@",opt2:"@STPLUSNO@:20",opt3:"@LFPLUSNO@:20",imgsrc:"dragonzombie.png",ani:"ball",com:"射撃：戦闘時ＳＴ＆ＨＰ＋20[アイテムを使用しない場合]"},
	C113:{id:"C113",ctype:"C",name:"トランプガード",	cost:70, color:1,st:20,lf:20,item:"W",opt1:"@AID@",imgsrc:"trumpguard.png",ani:"slash1",com:"加勢"},
	C114:{id:"C114",ctype:"C",name:"マーブル・Ｅ",		cost:60, color:1,st:0, lf:20,item:"W",walk:"T",opt1:"@MAPUNIQUE@",imgsrc:"elementalm.png",ani:"ball",com:"結界(すでに配置されているクリーチャーと同名のクリーチャーは召還不可となる)"},
	C115:{id:"C115",ctype:"C",name:"Ｓ・ウォーカー",	cost:70, color:1,st:0, lf:30,opt1:"@STEQUAL@:ENCLR10",imgsrc:"shadowwalker.png",com:"戦闘時ＳＴ＝(マップ上対戦相手の属性クリーチャー×10)"},
	//F
	C201:{id:"C201",ctype:"C",name:"ミノタウロス",		cost:60, color:2,st:30,lf:40,opt1:"@SMASH@",imgsrc:"minotaur.png",ani:"slash1",com:"強打"},
	C202:{id:"C202",ctype:"C",name:"スパークビー",		cost:70, color:2,st:20,lf:20,opt1:"@FLYING@", opt2:"@STPLUS@:BEE",imgsrc:"sparkbee",ani:"ball",com:"飛行：戦闘時ＳＴ＋(マップ上の「スパークビー」「スカウトビー」×10)"},
	C203:{id:"C203",ctype:"C",name:"ケルベロス",		cost:80, color:2,st:50,lf:30,opt1:"@FIRST@",imgsrc:"cerberus",ani:"bite",com:"先制"},
	C204:{id:"C204",ctype:"C",name:"パイロマンサー",	cost:70, color:2,st:30,lf:30,walk:"W",opt1:"@DIRECT@", opt2:"@FIREBALL@=70",imgsrc:"piromancer.png",ani:"ball",com:"貫通：◆火球(70G)対象領地に20ダメージ：使用クリーチャーに20ダメージ"},
	C205:{id:"C205",ctype:"C",name:"ファイア・Ｅ",		cost:60, plus:"F", color:2,st:0, lf:20,item:"W",walk:"T",opt1:"@MAPBTSTPLUS@:20",imgsrc:"elementalf.png",ani:"ball",com:"結界(戦闘時攻撃側ＳＴ＋20)"},
	C206:{id:"C206",ctype:"C",name:"ドワーフ",			cost:70, color:2,st:30,lf:30,opt1:"@HALFSHIELD@",imgsrc:"dwarf",ani:"slash1",com:"頑健(戦闘時相手から受けるダメージを半減する)"},
	C207:{id:"C207",ctype:"C",name:"キマイラ",			cost:70, color:2,st:40,lf:40,opt1:"@STEQUAL@:4CLR",opt2:"@LFEQUAL@:4CLR",imgsrc:"chimera",ani:"slash3",com:"戦闘時ＳＴ＆ＨＰ＝(相手の領地種類[火水地風]×20)"},
	C208:{id:"C208",ctype:"C",name:"ファイアウォール",	cost:60, color:2,st:0,lf:50,item:"W",walk:"TI",opt1:"@WALL@",imgsrc:"wallf",ani:"ball",com:"拠点"},
	C209:{id:"C209",ctype:"C",name:"イフリート",		cost:80, color:2,st:30,lf:40,item:"W",opt1:"@STEQUAL@:IFRIT",imgsrc:"ifrit.png",ani:"ball",com:"戦闘時ＳＴ＝(支配領地[火]×20)(最大100：最低0)"},
	C210:{id:"C210",ctype:"C",name:"レッドドラゴン",	cost:120,plus:"F", color:2,st:50,lf:50,opt1:"@FLYING@",opt2:"@LEGEND@",imgsrc:"reddragon.png",ani:"slash3",com:"飛行：召還制限(土地レベル2以上)"},
	C211:{id:"C211",ctype:"C",name:"ジャガーノート",	cost:70, color:2,st:40,lf:50,walk:"W",opt1:"@SLOW@",opt2:"@PUSH@=80",imgsrc:"juggernaut.png",ani:"ball",com:"後手：◆押出(80G)対象の隣接するクリーチャーを直線上が空き地に移動させる"},
	C212:{id:"C212",ctype:"C",name:"フェニックス",		cost:60, plus:"F", color:2,st:30,lf:30,item:"I",opt1:"@FLYING@",opt2:"@FENIX@=100",imgsrc:"fenix.png",ani:"slash3",com:"飛行：◆転生(100G)配置領地は売却後火属性土地になりデッキ復帰"},
	C213:{id:"C213",ctype:"C",name:"バーサーカー",		cost:70, color:2,st:40,lf:40,opt1:"@IRONHEART@!ATK",imgsrc:"berserker.png",ani:"slash1",com:"侵略戦闘時攻撃によりＨＰは0にならない"},
	C214:{id:"C214",ctype:"C",name:"マンティコア",		cost:80, plus:"F",color:2,st:40,lf:40,opt1:"@POISON@",opt2:"@UNTIELEMENT@=40",imgsrc:"manticore.png",ani:"slash3",com:"猛毒：◆無地(40G)対象クリーチャーは「無地」呪いとなる。"},
	C215:{id:"C215",ctype:"C",name:"ケットシー",		cost:80, color:2,st:30,lf:30,opt1:"@PROTECTION@!FLY",opt2:"@PROTECT@",imgsrc:"caitsith.png",ani:"slash3",com:"無効[飛行]：保護"},
	C216:{id:"C216",ctype:"C",name:"ボガート",			cost:60, color:2,st:10,lf:30,opt1:"@GREED@",opt2:"@PHANTASM@",imgsrc:"boggart.png",ani:"ball",com:"強欲(通行料×2.0)：幻影(マップＨＰ固定)"},
	C217:{id:"C217",ctype:"C",name:"ウォーロード",		cost:70, color:2,st:10,lf:30,opt1:"@MAPBTLFPLUSN@:20",imgsrc:"warlord.png",ani:"slash1",com:"結界(戦闘時ＨＰ＋20[無])"},
	C218:{id:"C218",ctype:"C",name:"バンディクート",	cost:70, plus:"F", color:2,st:30,lf:40,opt1:"@FIRST@",opt2:"@REWARD@",imgsrc:"bandicoot.png",ani:"slash3",com:"先制：侵略成功時土地レベルを１上昇させる"},
	//W
	C301:{id:"C301",ctype:"C",name:"マーフォーク",		cost:70, color:3,st:20,lf:30,item:"I",opt1:"@BAND@",imgsrc:"merfork",ani:"slash3",com:"援護"},
	C302:{id:"C302",ctype:"C",name:"クラーケン",		cost:80, color:3,st:20,lf:50,walk:"F",item:"I",opt1:"@REGENE@!TEW",opt2:"@DICE1@",imgsrc:"kraken",ani:"slash3",com:"再生[水領地]：戦闘終了時、相手に「ドゥームダイス１」呪いを付加"},
	C303:{id:"C303",ctype:"C",name:"リヴァイアサン",	cost:120,plus:"W",color:3,st:30,lf:50,opt1:"@DIRECT@!CLED",opt2:"@SMASH@!CLF",opt3:"@SINK@",imgsrc:"rivaisan",ani:"bite",com:"貫通[地風]：強打[火]：侵略成功時土地属性を水属性に変化させる"},
	C304:{id:"C304",ctype:"C",name:"ラミア",			cost:60, color:3,st:30,lf:30,opt1:"@DIVING@=20",opt2:"@SPY@",imgsrc:"lamia",ani:"slash3",com:"察知：◆潜水(20G)対象の水属性土地(空地)に移動"},
	C305:{id:"C305",ctype:"C",name:"バルーンアメーバ",	cost:50, color:3,st:10,lf:10,opt1:"@FLYING@",opt2:"@BALOON@",imgsrc:"baloon",ani:"ball",com:"飛行：◇膨張(プレイヤーが通過する度にＭＨＰ＋10、ＭＨＰが100以上になると破壊される)"},
	C306:{id:"C306",ctype:"C",name:"ウォーター・Ｅ",	cost:60, plus:"W",color:3,st:0, lf:20,item:"W",walk:"T",opt1:"@MAPBTINVALID@:30",imgsrc:"elementalw.png",ani:"ball",com:"結界(戦闘時基本ＳＴ30以下はＳＴ＝0)"},
	C307:{id:"C307",ctype:"C",name:"アイスウォール",	cost:60, color:3,st:0, lf:50,item:"W",walk:"TI",opt1:"@WALL@",imgsrc:"wallw",ani:"ball",com:"拠点"},
	C308:{id:"C308",ctype:"C",name:"ネクロマンサー",	cost:60, color:3,st:30,lf:30,opt1:"@RITUAL@=80",imgsrc:"necromancer",ani:"ball",com:"◆召喚(80G)マップ上のランダムな空き地にスケルトンを召喚する"},
	C309:{id:"C309",ctype:"C",name:"ケルピー",			cost:70, color:3,st:20,lf:40,item:"W",opt1:"@QUICKSAND@=100",imgsrc:"kelpie.png",ani:"slash3",com:"◆足止(100G)この領地を「足止」呪いにする"},
	C310:{id:"C310",ctype:"C",name:"リザードマン",		cost:70, color:3,st:30,lf:40,opt1:"@FIRST@",opt2:"@SHOOT@",imgsrc:"rizardman.png",ani:"slash1",com:"先制：射撃"},
	C311:{id:"C311",ctype:"C",name:"Ｓ・スライム",		cost:40, color:3,st:20,lf:20,walk:"FD",opt1:"@HALFSHIELD@",opt2:"@STICKY@",imgsrc:"stickyslime.png",ani:"ball",com:"頑健：戦闘破壊時手札に「Ｓ・スライム」を2枚得る"},
	C312:{id:"C312",ctype:"C",name:"メデューサ",		cost:70, color:3,st:30,lf:30,opt1:"@STONE@",opt2:"@PROTECTION@!CLN",imgsrc:"medusa.png",ani:"slash3",com:"即死[無]：無効[無]"},
	C313:{id:"C313",ctype:"C",name:"ウィザード",		cost:70, color:3,st:0, lf:30,item:"W",opt1:"@CURSEDMG@:30",opt2:"@DRAWCARD@=40",imgsrc:"wizard.png",ani:"ball",com:"呪術(戦闘終了時相手に30ダメージ)：◆補充(40G)カードを1枚引く"},
	C314:{id:"C314",ctype:"C",name:"パイレーツ",		cost:80, color:3,st:30,lf:20,walk:"ED",opt1:"@BAND@",opt2:"@DIRECT@!CLFW",imgsrc:"pirate.png",ani:"slash1",com:"援護：貫通[火水]"},
	C315:{id:"C315",ctype:"C",name:"バンシー",			cost:70, color:3,st:20,lf:30,walk:"I",opt1:"@FORGET@",opt2:"@DISPEL@=60",imgsrc:"bansee.png",ani:"slash3",com:"忘却：◆絶叫(60G)プレイヤー全員の呪いが消える"},
	C316:{id:"C316",ctype:"C",name:"ブラックナイト",	cost:70, color:3,st:40,lf:40,opt1:"@HUNTER@",imgsrc:"blackknight.png",ani:"slash1",com:"攻撃成功時武具を使用していた場合ダメージ分のGを奪う"},
	C317:{id:"C317",ctype:"C",name:"ノーチラス",		cost:50, color:3,st:40,lf:30,opt1:"@STPLUS@:10!CURSED",opt2:"@LFPLUS@:10!CURSED",imgsrc:"nautilus.png",ani:"ball",com:"戦闘時ＳＴ＆ＨＰ＋10[呪いがかかっている領地]"},
	//E
	C401:{id:"C401",ctype:"C",name:"Ｇ・フロッグ",		cost:60, color:4,st:30,lf:40,opt1:"@POISON@",opt2:"@SHOOT@",imgsrc:"gflog",ani:"slash3",com:"猛毒：射撃"},
	C402:{id:"C402",ctype:"C",name:"ガーゴイル",		cost:70, color:4,st:40,lf:40,walk:"T",opt1:"@DEFBASE@",imgsrc:"gargoyle",ani:"slash3",com:"防衛"},
	C403:{id:"C403",ctype:"C",name:"ケンタウロス",		cost:90, color:4,st:30,lf:30,opt1:"@BAND@",opt2:"@SHOOT@",imgsrc:"centaur.png",ani:"slash1",com:"援護：射撃"},
	C404:{id:"C404",ctype:"C",name:"ロックイーター",	cost:70, color:4,st:30,lf:30,item:"W",opt1:"@LFEQUAL@:TE20",imgsrc:"rockeater",ani:"bite",com:"戦闘時ＨＰ＝(所有地属性領地×20)"},
	C405:{id:"C405",ctype:"C",name:"アース・Ｅ",		cost:60 ,plus:"E",color:4,st:0, lf:20,item:"W",walk:"T",opt1:"@MAPTERRITORYLOCK@",imgsrc:"elementale.png",ani:"ball",com:"結界(領地移動不可)"},
	C406:{id:"C406",ctype:"C",name:"サスカッチ",		cost:110,color:4,st:60,lf:60,item:"WI",imgsrc:"fgiant",ani:"slash3"},
	C407:{id:"C407",ctype:"C",name:"ストーンウォール",	cost:60, color:4,st:0,lf:50,item:"W",walk:"TI",opt1:"@WALL@",imgsrc:"walle",ani:"ball",com:"拠点"},
	C408:{id:"C408",ctype:"C",name:"ドリアード",		cost:80, color:4,st:20,lf:30,item:"W",opt1:"@BAND@",opt2:"@PROTECT@",imgsrc:"driard.png",ani:"slash3",com:"援護：保護"},
	C409:{id:"C409",ctype:"C",name:"バジリスク",		cost:70, color:4,st:40,lf:40,opt1:"@DEATH@",imgsrc:"basilisk.png",ani:"bite",com:"即死(アイテム不使用時に相手が使用時)"},
	C410:{id:"C410",ctype:"C",name:"ドルイド",			cost:70, color:4,st:30,lf:30,opt1:"@RUST@=60",imgsrc:"druid.png",ani:"ball",com:"◆破砕(60G)相手プレイヤー全員の手札からアイテム[武具]をランダムに1枚破壊する"},
	C411:{id:"C411",ctype:"C",name:"エルフレンジャー",	cost:60, color:4,st:30,lf:30,opt1:"@SCOUT@",opt2:"@SPY@",imgsrc:"elvenranger.png",ani:"slash1",com:"察知：◇偵察(所有者通過時呪い状態でなければ「啓示」呪い(1ターン)となる)"},
	C412:{id:"C412",ctype:"C",name:"カーバンクル",		cost:70, color:4,st:20,lf:20,opt1:"@BAND@",opt2:"@REFLECT@",imgsrc:"carbuncle.png",ani:"slash3",com:"援護：反射"},
	C413:{id:"C413",ctype:"C",name:"フォレストマザー",	cost:100,plus:"E",color:4,st:20,lf:40,walk:"TI",opt1:"@LFPLUS@:20!TEE",opt2:"@WALL@",opt3:"@PHANTASM@",imgsrc:"fmother.png",ani:"ball",com:"戦闘時ＨＰ＋20[地領地]：拠点：幻影(マップＨＰ固定)"},
	C414:{id:"C414",ctype:"C",name:"タイタン",			cost:100,plus:"E",color:4,st:50,lf:50,opt1:"@SMASH@!LF50",imgsrc:"titan.png",ani:"ball",com:"強打[MAXHP50以上]"},
	C415:{id:"C415",ctype:"C",name:"ファンガス",		cost:70, color:4,st:20,lf:30,opt1:"@POISON@",opt2:"@DIVISION@=40",imgsrc:"fangus.png",ani:"ball",com:"猛毒：◆分裂(40G)"},
	C416:{id:"C416",ctype:"C",name:"エルフメイジ",		cost:60, plus:"E",color:4,st:30,lf:30,opt1:"@ADAPTATION@",imgsrc:"elvenlord.png",ani:"ball",com:"戦闘開始時条件を満たした分だけ能力を付加、先制[戦闘領地が地属性]、呪術[支配領地に隣接]、頑健[城砦に隣接]"},
	C417:{id:"C417",ctype:"C",name:"マスターパンダ",	cost:60, color:4,st:30,lf:40,item:"I",opt1:"@COUNTER@",imgsrc:"masterpanda.png",ani:"ball",com:"戦闘時攻撃ダメージを受けた後にＨＰが1以上あれば受けたダメージを相手に与える"},
	//D
	C501:{id:"C501",ctype:"C",name:"グリフォン",		cost:90, color:5,st:40,lf:30,opt1:"@FLYING@",imgsrc:"gliffin",ani:"slash3",com:"飛行"},
	C502:{id:"C502",ctype:"C",name:"ペガサス",			cost:80, color:5,st:30,lf:20,opt1:"@FLYING@",opt2:"@GLIDE@=60",imgsrc:"pegasus",ani:"slash3",com:"飛行：◆滑空(60G)対象のレベル１の土地に移動"},
	C503:{id:"C503",ctype:"C",name:"ナイト",			cost:70, color:5,st:40,lf:40,opt1:"@WEAPON@",imgsrc:"knight.png",ani:"slash1",com:"強打[武具使用時]"},
	C504:{id:"C504",ctype:"C",name:"スフィンクス",		cost:70, color:5,st:20,lf:50,opt1:"@FIRST@",opt2:"@SPHINX@",imgsrc:"sphinx",ani:"slash3",com:"先制：戦闘時ラウンド数が奇数ならＳＴ＋30＆ＨＰ－30、10の倍数ならＳＴ＋30"},
	C505:{id:"C505",ctype:"C",name:"サンドゴーレム",	cost:80, color:5,st:60,lf:60,opt1:"@LFPLUS@:RDEC",opt2:"@STPLUS@:RDEC",imgsrc:"sgolem",ani:"slash3",com:"戦闘時ＳＴ＆ＨＰ－(ラウンド数)"},
	C506:{id:"C506",ctype:"C",name:"エア・Ｅ",			cost:60, plus:"D", color:5,st:0, lf:20,item:"W",walk:"T",opt1:"@MAPBTFLYING@",imgsrc:"elementala.png",ani:"ball",com:"結界(戦闘時飛行はＳＴ＆ＨＰ＋10)"},
	C507:{id:"C507",ctype:"C",name:"ウィッチ",			cost:60, color:5,st:0,lf:30,item:"W",opt1:"@CURSEDMG@:30",opt2:"@DRAIN@=30",imgsrc:"witch",ani:"ball",com:"呪術(戦闘終了時相手に30ダメージ)：◆吸収(30G)対象プレイヤーの所持魔力の20%を奪う"},
	C508:{id:"C508",ctype:"C",name:"サンドウォール",	cost:60, color:5,st:0,lf:50,item:"W",walk:"TI",opt1:"@WALL@",imgsrc:"walld",ani:"ball",com:"拠点"},
	C509:{id:"C509",ctype:"C",name:"アークエンジェル",	cost:110,plus:"D",color:5,st:40,lf:40,item:"W",opt1:"@FLYING@",opt2:"@CLEAR@",opt3:"@REMOVE@=40",imgsrc:"archangelus.png",ani:"ball",com:"飛行：浄化：◆解呪(40G)対象領地の呪いを解除する"},
	C510:{id:"C510",ctype:"C",name:"ナイトメア",		cost:60, color:5,st:30,lf:30,opt1:"@NIGHTMARE@",imgsrc:"nightmare.png",ani:"ball",com:"周回ボーナス時ラウンド数をチェックする(奇数)ＳＴ＆ＨＰ＋10(最大70)：(偶数)隣接する空き地全てに自身をコピーする"},
	C511:{id:"C511",ctype:"C",name:"ハーピー",			cost:80, color:5,st:20,lf:30,walk:"E",opt1:"@FLYING@",opt2:"@BIND@",imgsrc:"harpy.png",ani:"slash3",com:"飛行：麻痺"},
	C512:{id:"C512",ctype:"C",name:"キュウビ",			cost:70, plus:"D",color:5,st:30,lf:40,walk:"TI",opt1:"@WALL@",opt2:"@PROTECT@",imgsrc:"ninetail.png",ani:"slash3",com:"拠点：保護"},
	C513:{id:"C513",ctype:"C",name:"グレムリン",		cost:60, color:5,st:30,lf:40,opt1:"@DISCARD@",imgsrc:"gremlin.png",ani:"slash3",com:"戦闘時攻撃成功した場合(ダメージが1以上)相手プレイヤーはランダムに手札を1枚破棄"},
	C514:{id:"C514",ctype:"C",name:"スカウトビー",		cost:70, color:5,st:20,lf:20,opt1:"@FLYING@",opt2:"@SPY@",opt3:"@TOUR@=20",imgsrc:"scoutbee.png",ani:"slash3",com:"飛行：察知：◆巡回(20G)対象の風属性土地(空地)に移動"},
	C515:{id:"C515",ctype:"C",name:"デュラハン",		cost:70, plus:"D",color:5,st:0,lf:40,opt1:"@STEQUAL@:CN10",opt2:"@LFEQUAL@:CN10",imgsrc:"dullahan.png",ani:"slash1",com:"戦闘時ＳＴ＆ＨＰ＝(マップ上の無属性クリーチャー×10)"},
	C516:{id:"C516",ctype:"C",name:"ウロボロス",		cost:90, color:5,st:40,lf:30,item:"I",opt1:"@UROBOROS@",imgsrc:"uroboros.png",ani:"bite",com:"戦闘破壊時領地数が最低の場合再召喚される"},
	C517:{id:"C517",ctype:"C",name:"ムシュフシュ",		cost:80, color:5,st:40,lf:40,walk:"E",opt1:"@POISON@", opt2:"@DIRECT@!POISON",imgsrc:"musus.png",ani:"bite",com:"猛毒：貫通[猛毒呪い]"},
	//ITEM
	I001:{id:"I001",ctype:"I",name:"ロングソード",		cost:40,item:"W",opt1:"STPLUS:40",imgsrc:"longsword",com:"ＳＴを40上昇させる"},
	I002:{id:"I002",ctype:"I",name:"プレートメイル",	cost:40,item:"W",opt1:"LFPLUS:40",imgsrc:"platemail",com:"ＨＰを40上昇させる"},
	I003:{id:"I003",ctype:"I",name:"ロングボウ",		cost:60,item:"W",opt1:"STPLUS:20",opt2:"FIRST",opt3:"SHOOT",imgsrc:"longbow.png",com:"ＳＴを20上昇させる：先制：射撃"},
	I004:{id:"I004",ctype:"I",name:"スレッジハンマー",	cost:60,item:"W",opt1:"STPLUS:30",opt2:"SMASH",opt3:"SLOW",imgsrc:"sledge.png",com:"ＳＴを30上昇させる：強打：後手"},
	I005:{id:"I005",ctype:"I",name:"アイアンハート",	cost:70,item:"I",opt1:"IRONHEART",imgsrc:"ironheart.png",com:"ＨＰを超えるダメージを受けた場合、ＨＰ＝1[はじめからＨＰ＝1の時は軽減できない]"},
	I006:{id:"I006",ctype:"I",name:"ホーリーストーン",	cost:100,item:"I",opt1:"HOLYSTONE",imgsrc:"holystone",com:"戦闘開始時相手の援護クリーチャー・アイテムカードを破壊する"},
	I007:{id:"I007",ctype:"I",name:"アサシンクローク",	cost:40,item:"I",opt1:"STPLUS:40!NOITEM",opt2:"LFPLUS:40!NOITEM",imgsrc:"assassin",com:"相手がアイテムカード未使用時、ＳＴ＆ＨＰを40上昇させる"},
	I008:{id:"I008",ctype:"I",name:"イビルストーン",	cost:60,item:"I",opt1:"EVILSTONE",imgsrc:"evilstone",com:"戦闘時相手クリーチャーの能力が発生しなくなる"},
	I009:{id:"I009",ctype:"I",name:"ディバイン・Ｓ",	cost:60,item:"I",opt1:"DIVINESTONE",imgsrc:"divinestone",com:"ダメージを1/2跳ね返す"},
	I010:{id:"I010",ctype:"I",name:"バックラー",		cost:40,item:"W",opt1:"LFPLUS:20",opt2:"STMINUS:20",opt3:"BACKHAND",imgsrc:"buckler.png",com:"ＳＴ－20：ＨＰ＋20：手札復帰"},
	I011:{id:"I011",ctype:"I",name:"スピア",			cost:60,item:"W",opt1:"LFPLUS:20",opt2:"STPLUS:20",opt3:"SHOOT",imgsrc:"spear.png",com:"ＳＴ＋20：ＨＰ＋20：射撃"},
	I012:{id:"I012",ctype:"I",name:"コールドストーン",	cost:40,item:"I",opt1:"STEQUAL:50",opt2:"LFEQUAL:50",imgsrc:"coldstone.png",com:"ＳＴ＝50：ＨＰ＝50"},
	I013:{id:"I013",ctype:"I",name:"フェザークラウン",	cost:40,item:"I",opt1:"FIRST",opt2:"BACKHAND",imgsrc:"feathercrown.png",com:"先制：手札復帰"},
	I014:{id:"I014",ctype:"I",name:"オオダチ",			cost:80,item:"W",opt1:"STPLUS:HANDM80",imgsrc:"ootachi.png",com:"ＳＴ＋80－(自分の手札枚数×10)"},
	I015:{id:"I015",ctype:"I",name:"ブラックスワン",	cost:0, item:"I",opt1:"BLACKSWAN",imgsrc:"blackswan.png",com:"戦闘終了時対戦相手が生存していればHP×10Gを得る"},
	I016:{id:"I016",ctype:"I",name:"レイピア",			cost:30,item:"W",opt1:"STPLUS:30",opt2:"REVDEATH",imgsrc:"rapier.png",com:"ＳＴを30上昇させる：雪辱[即死]"},
	I017:{id:"I017",ctype:"I",name:"イージス",			cost:60,item:"W",opt1:"LFPLUS:20",opt2:"AEGIS",imgsrc:"aegis.png",com:"ＨＰ＋20：無効[相手が武具使用時]"},
	//SPELL
	S001:{id:"S001",ctype:"S",name:"マナ",				cost:0,  spell:"MANA",		tgt:"AMP",imgsrc:"mana",com:"周回数×50Gを得る"},
	S002:{id:"S002",ctype:"S",name:"ドゥームダイス１",	cost:30, spell:"SETSTATUSP",tgt:"TEP",opt1:"_DICE_:1",opt2:1,imgsrc:"magicdice1.png",com:"(呪い1ターン)対象プレイヤーのダイスは1になる"},
	S003:{id:"S003",ctype:"S",name:"ドゥームダイス７",	cost:60, spell:"SETSTATUSP",tgt:"TEP",opt1:"_DICE_:7",opt2:1,imgsrc:"magicdice7.png",com:"(呪い1ターン)対象プレイヤーのダイスは7になる"},
	S004:{id:"S004",ctype:"S",name:"ホープ",			cost:40, spell:"DRAW",		tgt:"AMP",opt1:2,imgsrc:"hope",com:"カードを2枚引く"},
	S005:{id:"S005",ctype:"S",name:"ヒール",			cost:30, spell:"HEAL",		tgt:"TEGALL",imgsrc:"heal",com:"対象クリーチャーのHPを全回復し、全ての呪いを解除する：デッキ復帰"},
	S006:{id:"S006",ctype:"S",name:"シャッター",		cost:60, spell:"SHUTTER",	tgt:"TOP",imgsrc:"shatter.png",com:"対象プレイヤーのアイテムカード、スペルカードの内1枚を選択して破壊する"},
	S007:{id:"S007",ctype:"S",name:"アップヒーバル",	cost:150,spell:"COLORCHANGE",tgt:"TEG",opt1:2,imgsrc:"colorf",com:"対象の領地を火属性に変える"},
	S008:{id:"S008",ctype:"S",name:"シンク",			cost:150,spell:"COLORCHANGE",tgt:"TEG",opt1:3,imgsrc:"colorw",com:"対象の領地を水属性に変える"},
	S009:{id:"S009",ctype:"S",name:"ワイルドグロース",	cost:150,spell:"COLORCHANGE",tgt:"TEG",opt1:4,imgsrc:"colore",com:"対象の領地を地属性に変える"},
	S010:{id:"S010",ctype:"S",name:"ウェザリング",		cost:150,spell:"COLORCHANGE",tgt:"TEG",opt1:5,imgsrc:"colord",com:"対象の領地を風属性に変える"},
	S011:{id:"S011",ctype:"S",name:"リンカネーション",	cost:40, spell:"REINCARNE"	,tgt:"AMP",imgsrc:"reincarne",com:"手札を全て破棄して、破棄枚数+1枚を引く"},
	S012:{id:"S012",ctype:"S",name:"マジックボルト",	cost:60, spell:"DAMAGE",	tgt:"TOG",opt1:20,imgsrc:"magicbolt",com:"対象クリーチャーに20ダメージ"},
	S013:{id:"S013",ctype:"S",name:"バンク",			cost:0,  spell:"SETSTATUSP",tgt:"AMP",opt1:"_BANK_:250", opt2:2, imgsrc:"bank",com:"(呪い2ターン)2ターン後に250Gを得る"},
	S014:{id:"S014",ctype:"S",name:"インスペクション",	cost:40, spell:"INSPECTION",tgt:"AOP",imgsrc:"inspection",com:"相手全員からアイテムカード枚数×30Gを奪う(可能なかぎり)"},
	S015:{id:"S015",ctype:"S",name:"マーケット",		cost:40, spell:"MARKET",	tgt:"AOP",imgsrc:"market",com:"相手全員の手札からスペルカードを各2枚ランダムに表示し、選択したカードを取得して所有者に80G支払う"},
	S016:{id:"S016",ctype:"S",name:"ドレインマジック",	cost:80, spell:"DRAIN",		tgt:"TOP",opt1:30,imgsrc:"drain",com:"対象プレイヤーの所持魔力の30%を奪う"},
	S017:{id:"S017",ctype:"S",name:"テレポート",		cost:40, spell:"TELEPORT",	tgt:"AMP",opt1:"special",imgsrc:"teleport",com:"一番近い特殊地形に移動する(複数存在する場合は選択)(ダイス使用不可)"},
	S018:{id:"S018",ctype:"S",name:"バインド",			cost:60, spell:"SETSTATUSG",tgt:"TEG",opt1:"_BIND_",opt2:99,imgsrc:"bind",com:"(呪い)対象のクリーチャーは「麻痺」呪いとなる"},
	S019:{id:"S019",ctype:"S",name:"フリング",			cost:50, spell:"FLING",		tgt:"TSG",imgsrc:"fling",com:"使用者が支配領地上にいる場合、配置クリーチャーを対象の空き土地に移動する：デッキ復帰"},
	S020:{id:"S020",ctype:"S",name:"フォージリィ",		cost:80, spell:"SETSTATUSP",tgt:"AMP",opt1:"_FORGERY_",opt2:99,imgsrc:"forgery",com:"(呪い城まで)通過砦に関わらず城到着にて周回となる：基礎ボーナス×1.5：砦ボーナスが受け取れない"},
	S021:{id:"S021",ctype:"S",name:"プロテクト",		cost:70, spell:"SETSTATUSG",tgt:"TEG",opt1:"_PROTECT_",opt2:99,imgsrc:"protect.png",com:"(呪い)対象の領地はスペル、領地能力の対象に選択できない"},
	S022:{id:"S022",ctype:"S",name:"アンサモン",		cost:140,spell:"UNSUMMON",	tgt:"TOG",imgsrc:"unsummon",com:"対象のダメージを受けているクリーチャーを使用者の手札に戻す"},
	S023:{id:"S023",ctype:"S",name:"ナビゲート",		cost:50, spell:"SETSTATUSP",tgt:"AMP",opt1:"_NAVIGATE_",opt2:2,imgsrc:"navigate",com:"(呪い2ターン)ダイスの結果を二つから選択できる"},
	S024:{id:"S024",ctype:"S",name:"ディザスター",		cost:200,spell:"AREADMG",	tgt:"AEGMASS",opt1:20,imgsrc:"dizaster",com:"マップ上に最も多い属性土地にいるクリーチャー全てに20ダメージ"},
	S025:{id:"S025",ctype:"S",name:"リコンストラクト",	cost:80 ,spell:"SETSTATUSG",tgt:"TEG",opt1:"_RECONSTRUCT_",opt2:99,opt3:"draw",imgsrc:"reconstruct",com:"(呪い)対象領地上でターン終了された場合、基本土地価値が10上昇(最大200)：カードを１枚引く"},
	S026:{id:"S026",ctype:"S",name:"フェスティバル",	cost:0,  spell:"FESTIVAL",	tgt:"AMP",opt1:150,imgsrc:"festival.png",com:"使用者は手札のクリーチャーカードを全て破棄し、破棄枚数×150Gを得る"},
	S027:{id:"S027",ctype:"S",name:"テレグノーシス",	cost:70, spell:"SETSTATUSP",tgt:"AMP",opt1:"_TELEGNOSIS_", opt2:2, imgsrc:"telegnosis",com:"(呪い2ターン)領地コマンド時全ての自領地を選択できる"},
	S028:{id:"S028",ctype:"S",name:"アースクエイク",	cost:250,spell:"EARTHQUAKE",tgt:"AEGGRD",imgsrc:"earthquake",com:"手札から「アースクエイク」を全て破棄：飛行を持たないクリーチャー全てに10＋(破棄枚数×10)ダメージ(最大30)"},
	S029:{id:"S029",ctype:"S",name:"フォーサイト",		cost:40, spell:"FORESIGHT",	tgt:"AMP",opt1:4,imgsrc:"foresight",com:"デッキの上から4枚確認して選択した1枚を引く(デッキの残り枚数以上は確認できない)"},
	S030:{id:"S030",ctype:"S",name:"ショートカット",	cost:30, spell:"SETSTATUSP",tgt:"AMP",opt1:"_SHORTCUT_:3",opt2:3,imgsrc:"shortcut",com:"(呪い3ターン)ダイスの最大値をマップの最大値＋3"},
	S031:{id:"S031",ctype:"S",name:"ジェイル",			cost:80, spell:"SETSTATUSG",tgt:"TEG",opt1:"_JAIL_",opt2:99,imgsrc:"jail",com:"(呪い)対象の領地は戦闘不可となり通行料が発生しない：領地コマンド「レベルアップ」「地形変化」が行えない"},
	S032:{id:"S032",ctype:"S",name:"プレイグ",			cost:70, spell:"SETSTATUSP",tgt:"TEP",opt1:"_PLAGUE_",opt2:2,imgsrc:"plague",com:"(呪い2ターン)対象プレイヤーは「疫病」呪いとなる(疫病呪いのプレイヤーが通過した領地は「猛毒」呪いとなる)"},
	S033:{id:"S033",ctype:"S",name:"フラットライン",	cost:60, spell:"FLATLINE",	tgt:"AEP",imgsrc:"flatline",com:"プレイヤー全員の手札は4枚となるようにデッキからドローまたは手札がランダム破棄される。"},
	S034:{id:"S034",ctype:"S",name:"エクスチェンジ",	cost:30, spell:"EXCHANGE",	tgt:"TMG,TOG",imgsrc:"exchange.png",com:"対象の支配クリーチャー1体と対象の相手クリーチャー１体のＳＴを入れ替える：デッキ復帰"},
	S035:{id:"S035",ctype:"S",name:"バリアー",			cost:60, spell:"SETSTATUSP",tgt:"AMP",opt1:"_BARRIER_",opt2:6,imgsrc:"barrier.png",com:"(呪い4ターン)使用者は対象を取るスペル・領地能力の対象にならない"},
	S036:{id:"S036",ctype:"S",name:"リリーフ",			cost:30, spell:"RELIEF",	tgt:"TMG,TMG",imgsrc:"relief.png",com:"対象の支配クリーチャーを2体選択し位置を入れ替える：デッキ復帰"},
	S037:{id:"S037",ctype:"S",name:"インシネレイト",	cost:70, spell:"INCINERATE",tgt:"TOG",opt1:10,imgsrc:"incinerate.png",com:"対象クリーチャーに10＋(既に使用された「インシネレイト」の枚数×10)ダメージ(最大40)"},
	S038:{id:"S038",ctype:"S",name:"コンプレッション",	cost:40, spell:"COMPRESSION",tgt:"TEP",imgsrc:"compression.png",com:"対象プレイヤーのデッキの上から5枚確認して選択したカードまで上から破棄する。"},
	S039:{id:"S039",ctype:"S",name:"コントラクト",		cost:120,spell:"CONTRACT",	tgt:"TEG",imgsrc:"contract.png",com:"MHP－20：(呪い)通行料が所有者の最大通行料と同額となる"},
	S040:{id:"S040",ctype:"S",name:"パニッシャー",		cost:150,spell:"AREADMG",	tgt:"AEGCURSED",opt1:20,imgsrc:"panisher.png",com:"呪い状態のクリーチャー全てに20ダメージ"},
	S041:{id:"S041",ctype:"S",name:"テレパシー",		cost:50, spell:"SETSTATUSG",tgt:"TEG",opt1:"_TELEPATHY_",opt2:99,imgsrc:"telepathy.png",com:"(呪い)常に領地コマンド対象となる：領地コマンド使用時呪い解除"},
	//d.push({id:"S042",ctype:"S",name:"リンクゲート",		cost:60, spell:"LINKGATE",	tgt:"AMG",opt1:"_LINKGATE_",opt2:99,imgsrc:"linkgate.png",com:"(呪い)対象の属性色の支配領地は転送呪い(この領地に停止時支配領地なら他の転送呪いに移動可)となる"});
	S043:{id:"S043",ctype:"S",name:"バランス",			cost:30, spell:"BALANCE",	tgt:"AEP",imgsrc:"balance.png",com:"全てのプレイヤーは順位×領地数×20Gを得る"},
	S044:{id:"S044",ctype:"S",name:"グラビティ",		cost:70, spell:"SETSTATUSG",tgt:"TEG",opt1:"_GRAVITY_",opt2:99,opt3:"draw",imgsrc:"gravity.png",com:"(呪い)対象のクリーチャーは「重力」呪い(領地移動不可：戦闘時ＳＴ－10、ＨＰ＋10)となる：カードを1枚引く"},
	S045:{id:"S045",ctype:"S",name:"オブリビオン",		cost:40, spell:"SETSTATUSG",tgt:"TEG",opt1:"_FORGET_",opt2:99,imgsrc:"oblivion.png",com:"(呪い)対象のクリーチャーは「忘却」呪いとなる"},
	S046:{id:"S046",ctype:"S",name:"フラクチャー",		cost:150,spell:"FRACTURE",	tgt:"TEG",imgsrc:"fracture.png",com:"対象の領地はレベル1にする：その後所有者のランダムな土地1つを下降したレベル分レベル上昇する"},
	S047:{id:"S047",ctype:"S",name:"エスケープ",		cost:20, spell:"TELEPORT",	tgt:"AMP",opt1:"escape",imgsrc:"escape.png",com:"使用者は一番近い空き地に移動する(複数存在する場合は選択)(ダイス使用不可)"},
	S048:{id:"S048",ctype:"S",name:"ハリケーン",		cost:120,spell:"AREASTATUS",tgt:"AEGFLY",opt1:"_BIND_",opt2:2,imgsrc:"hurricane.png",com:"(呪い2ターン)飛行を持つクリーチャーは全て「麻痺」呪いとなる"},
	S049:{id:"S049",ctype:"S",name:"ウォークライ",		cost:60, spell:"SETSTATUSP",tgt:"AMP",opt1:"_WARCRY_",opt2:99,imgsrc:"warcry.png",com:"(呪い)使用者は「行軍」呪いとなる(ターン開始時のドローカードを公開：クリーチャーだった場合コスト分のＧを得る)"},
	S050:{id:"S050",ctype:"S",name:"ソウルコレクト",	cost:10, spell:"SOULCOLECT",tgt:"AMP",opt1:40,imgsrc:"soulcolect.png",com:"破壊クリーチャー数×40Gを得る：破壊クリーチャー数は0となる"},
	S051:{id:"S051",ctype:"S",name:"ギャザー",			cost:0,  spell:"SETSTATUSP",tgt:"AMP",opt1:"_GATHER_",opt2:3,imgsrc:"gather.png",com:"(呪い3ターン)対象プレイヤーは「収集」呪いとなる"},
	S052:{id:"S052",ctype:"S",name:"ルイン",			cost:100,spell:"RUIN",		tgt:"AEP",imgsrc:"ruin.png",com:"プレイヤー全員の手札にあるアイテムカード[道具]を破壊する"},
	S053:{id:"S053",ctype:"S",name:"スワンプ",			cost:120,spell:"SETSTATUSG",tgt:"TEG",opt1:"_SWAMP_",opt2:4,imgsrc:"swamp.png",com:"(呪い4ターン)対象領地の地価は70%となる"},
	S054:{id:"S054",ctype:"S",name:"インフルエンス",	cost:80, spell:"INFLUENCE",	tgt:"TEG",imgsrc:"influence.png",com:"対象の領地を所有者が最も所持している属性に変える"},
	S055:{id:"S055",ctype:"S",name:"ディストーション",	cost:70, spell:"DISTORTION",tgt:"TEG",imgsrc:"distortion.png",com:"対象のクリーチャーはデッキ内のランダムなクリーチャーと交換される"},
	S056:{id:"S056",ctype:"S",name:"モノポリー",		cost:120,spell:"MONOPOLY",	tgt:"AMP",opt1:"_MONOPOLY_",opt2:1,imgsrc:"monopoly.png",com:"(呪い1ターン)使用者は「独占」呪いとなる(通行料を全て奪う)：他のプレイヤー「独占」呪いを解除"},
	S057:{id:"S057",ctype:"S",name:"スピリットウォーク",cost:20, spell:"SETSTATUSG",tgt:"TEG",opt1:"_SPIRITWALK_",opt2:99,imgsrc:"spiritwalk.png",com:"(呪い)対象のクリーチャーは「跳躍」呪いとなる"},
	S058:{id:"S058",ctype:"S",name:"リサーチ",			cost:40, spell:"DRAW",		tgt:"AMP",opt1:1,opt2:"hand",imgsrc:"research.png",com:"カードを1枚引く：手札復帰"},
	S059:{id:"S059",ctype:"S",name:"クエスト",			cost:20, spell:"QUEST",		tgt:"AMP",opt1:"_QUEST_",opt2:3,imgsrc:"quest.png",com:"(呪い3ターン)使用者は「冒険」呪いとなる(侵略成功時呪い以降の侵略成功回数×200Gを得て期間が再び3ターンとなる：最大3回)"},
	S060:{id:"S060",ctype:"S",name:"アップドラフト",	cost:80, spell:"AREASTATUS",tgt:"AEGHP30",opt1:"_SPIRITWALK_",imgsrc:"updraft.png",com:"(呪い)ＭＨＰが30以下のクリーチャーは「跳躍」呪いとなる"},
	//S061:{id:"S061",ctype:"S",name:"プライア",			cost:60, spell:"SETSTATUSP",tgt:"AMP",opt1:"_PRAYER_",opt2:1,imgsrc:"testspell",com:"(呪い1ターン)使用者は「祈願」呪いとなる(土地レベルアップコストが1/2となる)"},
	//返却値
	ZZZ:{}
}
