function CardDataSet(){
	var d = new Array();
	//CREATURE N
	d.push({id:"C101",type:"C",name:"ファイター",		cost:40, color:1,st:40,lf:40,opt1:"@PROTECTION@!CLN",img:"fighter.png",ani:"slash1",com:"無効[無]"});
	d.push({id:"C102",type:"C",name:"オーク",			cost:50, color:1,st:50,lf:50,opt1:"@SLOW@",img:"orc.png",ani:"slash1",com:"後手"});
	d.push({id:"C103",type:"C",name:"Ｇ・レイブン",		cost:40, color:1,st:20,lf:20,opt1:"@FLYING@",img:"gcrow",ani:"slash3",com:"飛行"});
	d.push({id:"C104",type:"C",name:"タワー",			cost:60, color:1,st:0, lf:40,item:"W",walk:"TI",opt1:"@DEFBASE@",opt2:"@LEVELUP@=150",img:"tower.png",ani:"ball",com:"防衛：◆改築(150G)この領地のレベルを1上昇させる"});
	d.push({id:"C105",type:"C",name:"ニンジャ",			cost:80, color:1,st:40,lf:40,opt1:"@FIRST@",opt2:"@POISON@",img:"ninja.png",ani:"slash1",com:"先制：猛毒"});
	d.push({id:"C106",type:"C",name:"スケルトン",		cost:40, color:1,st:20,lf:40,opt1:"@REGENE@",img:"skelton",com:"再生"});
	d.push({id:"C107",type:"C",name:"アルケミスト",		cost:50, color:1,st:30,lf:30,item:"W",opt1:"@ALCHEMY@=60",img:"alchemist.png",com:"◆錬金(60G)最後に使われたスペルを手札に追加する"});
	d.push({id:"C108",type:"C",name:"ラットヒーロー",	cost:50, color:1,st:20,lf:20,opt1:"@FIRST@",opt2:"@WEAPON@",opt3:"@ESCAPE@",img:"rathero.png",ani:"slash1",com:"先制：強打[武具使用時]：逃走"});
	d.push({id:"C109",type:"C",name:"クロム・Ｅ",		cost:60, color:1,st:0, lf:20,item:"W",walk:"T",opt1:"@MAPDMGREDUCE@",img:"elementalc.png",ani:"ball",com:"結界(スペルと領地能力によるダメージが10減少する)"});
	d.push({id:"C110",type:"C",name:"シーフ",			cost:60, color:1,st:30,lf:30,opt1:"@STEAL@",opt2:"@SPY@",img:"thief.png",ani:"slash1",com:"察知：◇奪取"});
	d.push({id:"C111",type:"C",name:"ジャックランタン",	cost:50, color:1,st:0, lf:30,opt1:"@SWAP@",img:"jolantan.png",ani:"ball",com:"戦闘終了時相手のＳＴとＭＨＰを入れ替える"});
	d.push({id:"C112",type:"C",name:"ドラゴンゾンビ",	cost:100,color:1,st:30,lf:30,opt1:"@SHOOT@",opt2:"@STPLUSNO@:20",opt3:"@LFPLUSNO@:20",img:"dragonzombie.png",ani:"ball",com:"射撃：戦闘時ＳＴ＆ＨＰ＋20[アイテムを使用しない場合]"});
	d.push({id:"C113",type:"C",name:"トランプガード",	cost:70, color:1,st:20,lf:20,item:"W",opt1:"@AID@",img:"trumpguard.png",ani:"slash1",com:"加勢"});
	d.push({id:"C114",type:"C",name:"マーブル・Ｅ",		cost:60, color:1,st:0, lf:20,item:"W",walk:"T",opt1:"@MAPUNIQUE@",img:"elementalm.png",ani:"ball",com:"結界(すでに配置されているクリーチャーと同名のクリーチャーは召還不可となる)"});
	d.push({id:"C115",type:"C",name:"Ｓ・ウォーカー",	cost:70, color:1,st:0, lf:30,opt1:"@STEQUAL@:ENCLR10",img:"shadowwalker.png",com:"戦闘時ＳＴ＝(マップ上対戦相手の属性クリーチャー×10)"});
	//F
	d.push({id:"C201",type:"C",name:"ミノタウロス",		cost:60, color:2,st:30,lf:40,opt1:"@SMASH@",img:"minotaur.png",ani:"slash1",com:"強打"});
	d.push({id:"C202",type:"C",name:"スパークビー",		cost:70, color:2,st:20,lf:20,opt1:"@FLYING@", opt2:"@STPLUS@:BEE",img:"sparkbee",ani:"ball",com:"飛行：戦闘時ＳＴ＋(マップ上の「スパークビー」「スカウトビー」×10)"});
	d.push({id:"C203",type:"C",name:"ケルベロス",		cost:80, color:2,st:50,lf:30,opt1:"@FIRST@",img:"cerberus",ani:"bite",com:"先制"});
	d.push({id:"C204",type:"C",name:"パイロマンサー",	cost:70, color:2,st:30,lf:30,walk:"W",opt1:"@DIRECT@", opt2:"@FIREBALL@=70",img:"piromancer.png",ani:"ball",com:"貫通：◆火球(70G)対象領地に20ダメージ：使用クリーチャーに20ダメージ"});
	d.push({id:"C205",type:"C",name:"ファイア・Ｅ",		cost:60, plus:"F", color:2,st:0, lf:20,item:"W",walk:"T",opt1:"@MAPBTSTPLUS@:20",img:"elementalf.png",ani:"ball",com:"結界(戦闘時攻撃側ＳＴ＋20)"});
	d.push({id:"C206",type:"C",name:"ドワーフ",			cost:70, color:2,st:30,lf:30,opt1:"@HALFSHIELD@",img:"dwarf",ani:"slash1",com:"頑健(戦闘時相手から受けるダメージを半減する)"});
	d.push({id:"C207",type:"C",name:"キマイラ",			cost:70, color:2,st:40,lf:40,opt1:"@STEQUAL@:4CLR",opt2:"@LFEQUAL@:4CLR",img:"chimera",ani:"slash3",com:"戦闘時ＳＴ＆ＨＰ＝(相手の領地種類[火水地風]×20)"});
	d.push({id:"C208",type:"C",name:"ファイアウォール",	cost:60, color:2,st:0,lf:50,item:"W",walk:"TI",opt1:"@WALL@",img:"wallf",ani:"ball",com:"拠点"});
	d.push({id:"C209",type:"C",name:"イフリート",		cost:80, color:2,st:30,lf:40,item:"W",opt1:"@STEQUAL@:IFRIT",img:"ifrit.png",ani:"ball",com:"戦闘時ＳＴ＝(支配領地[火]×20)(最大100：最低0)"});
	d.push({id:"C210",type:"C",name:"レッドドラゴン",	cost:120,plus:"F", color:2,st:50,lf:50,opt1:"@FLYING@",opt2:"@LEGEND@",img:"reddragon.png",ani:"slash3",com:"飛行：召還制限(土地レベル2以上)"});
	d.push({id:"C211",type:"C",name:"ジャガーノート",	cost:70, color:2,st:40,lf:50,walk:"W",opt1:"@SLOW@",opt2:"@PUSH@=80",img:"juggernaut.png",ani:"ball",com:"後手：◆押出(80G)対象の隣接するクリーチャーを直線上が空き地に移動させる"});
	d.push({id:"C212",type:"C",name:"フェニックス",		cost:60, plus:"F", color:2,st:30,lf:30,item:"I",opt1:"@FLYING@",opt2:"@FENIX@=100",img:"fenix.png",ani:"slash3",com:"飛行：◆転生(100G)配置領地は売却後火属性土地になりデッキ復帰"});
	d.push({id:"C213",type:"C",name:"バーサーカー",		cost:70, color:2,st:40,lf:40,opt1:"@IRONHEART@!ATK",img:"berserker.png",ani:"slash1",com:"侵略戦闘時攻撃によりＨＰは0にならない"});
	d.push({id:"C214",type:"C",name:"マンティコア",		cost:80, plus:"F",color:2,st:40,lf:40,opt1:"@POISON@",opt2:"@UNTIELEMENT@=40",img:"manticore.png",ani:"slash3",com:"猛毒：◆無地(40G)対象クリーチャーは「無地」呪いとなる。"});
	d.push({id:"C215",type:"C",name:"ケットシー",		cost:80, color:2,st:30,lf:30,opt1:"@PROTECTION@!FLY",opt2:"@PROTECT@",img:"caitsith.png",ani:"slash3",com:"無効[飛行]：保護"});
	d.push({id:"C216",type:"C",name:"ボガート",			cost:60, color:2,st:10,lf:30,opt1:"@GREED@",opt2:"@PHANTASM@",img:"boggart.png",ani:"ball",com:"強欲(通行料×2.0)：幻影(マップＨＰ固定)"});
	d.push({id:"C217",type:"C",name:"ウォーロード",		cost:70, color:2,st:10,lf:30,opt1:"@MAPBTLFPLUSN@:20",img:"warlord.png",ani:"slash1",com:"結界(戦闘時ＨＰ＋20[無])"});
	d.push({id:"C218",type:"C",name:"バンディクート",	cost:70, plus:"F", color:2,st:30,lf:40,opt1:"@FIRST@",opt2:"@REWARD@",img:"bandicoot.png",ani:"slash3",com:"先制：侵略成功時土地レベルを１上昇させる"});
	//W
	d.push({id:"C301",type:"C",name:"マーフォーク",		cost:70, color:3,st:20,lf:30,item:"I",opt1:"@BAND@",img:"merfork",ani:"slash3",com:"援護"});
	d.push({id:"C302",type:"C",name:"クラーケン",		cost:80, color:3,st:20,lf:50,walk:"F",item:"I",opt1:"@REGENE@!TEW",opt2:"@DICE1@",img:"kraken",ani:"slash3",com:"再生[水領地]：戦闘終了時、相手に「ドゥームダイス１」呪いを付加"});
	d.push({id:"C303",type:"C",name:"リヴァイアサン",	cost:120,plus:"W",color:3,st:30,lf:50,opt1:"@DIRECT@!CLED",opt2:"@SMASH@!CLF",opt3:"@SINK@",img:"rivaisan",ani:"bite",com:"貫通[地風]：強打[火]：侵略成功時土地属性を水属性に変化させる"});
	d.push({id:"C304",type:"C",name:"ラミア",			cost:60, color:3,st:30,lf:30,opt1:"@DIVING@=20",opt2:"@SPY@",img:"lamia",ani:"slash3",com:"察知：◆潜水(20G)対象の水属性土地(空地)に移動"});
	d.push({id:"C305",type:"C",name:"バルーンアメーバ",	cost:50, color:3,st:10,lf:10,opt1:"@FLYING@",opt2:"@BALOON@",img:"baloon",ani:"ball",com:"飛行：◇膨張(プレイヤーが通過する度にＭＨＰ＋10、ＭＨＰが100以上になると破壊される)"});
	d.push({id:"C306",type:"C",name:"ウォーター・Ｅ",	cost:60, plus:"W",color:3,st:0, lf:20,item:"W",walk:"T",opt1:"@MAPBTINVALID@:30",img:"elementalw.png",ani:"ball",com:"結界(戦闘時基本ＳＴ30以下はＳＴ＝0)"});
	d.push({id:"C307",type:"C",name:"アイスウォール",	cost:60, color:3,st:0, lf:50,item:"W",walk:"TI",opt1:"@WALL@",img:"wallw",ani:"ball",com:"拠点"});
	d.push({id:"C308",type:"C",name:"ネクロマンサー",	cost:60, color:3,st:30,lf:30,opt1:"@RITUAL@=80",img:"necromancer",ani:"ball",com:"◆召喚(80G)マップ上のランダムな空き地にスケルトンを召喚する"});
	d.push({id:"C309",type:"C",name:"ケルピー",			cost:70, color:3,st:20,lf:40,item:"W",opt1:"@QUICKSAND@=100",img:"kelpie.png",ani:"slash3",com:"◆足止(100G)この領地を「足止」呪いにする"});
	d.push({id:"C310",type:"C",name:"リザードマン",		cost:70, color:3,st:30,lf:40,opt1:"@FIRST@",opt2:"@SHOOT@",img:"rizardman.png",ani:"slash1",com:"先制：射撃"});
	d.push({id:"C311",type:"C",name:"Ｓ・スライム",		cost:40, color:3,st:20,lf:20,walk:"FD",opt1:"@HALFSHIELD@",opt2:"@STICKY@",img:"stickyslime.png",ani:"ball",com:"頑健：戦闘破壊時手札に「Ｓ・スライム」を2枚得る"});
	d.push({id:"C312",type:"C",name:"メデューサ",		cost:70, color:3,st:30,lf:30,opt1:"@STONE@",opt2:"@PROTECTION@!CLN",img:"medusa.png",ani:"slash3",com:"即死[無]：無効[無]"});
	d.push({id:"C313",type:"C",name:"ウィザード",		cost:70, color:3,st:0, lf:30,item:"W",opt1:"@CURSEDMG@:30",opt2:"@DRAWCARD@=40",img:"wizard.png",ani:"ball",com:"呪術(戦闘終了時相手に30ダメージ)：◆補充(40G)カードを1枚引く"});
	d.push({id:"C314",type:"C",name:"パイレーツ",		cost:80, color:3,st:30,lf:20,walk:"ED",opt1:"@BAND@",opt2:"@DIRECT@!CLFW",img:"pirate.png",ani:"slash1",com:"援護：貫通[火水]"});
	d.push({id:"C315",type:"C",name:"バンシー",			cost:70, color:3,st:20,lf:30,walk:"I",opt1:"@FORGET@",opt2:"@DISPEL@=60",img:"bansee.png",ani:"slash3",com:"忘却：◆絶叫(60G)プレイヤー全員の呪いが消える"});
	d.push({id:"C316",type:"C",name:"ブラックナイト",	cost:70, color:3,st:40,lf:40,opt1:"@HUNTER@",img:"blackknight.png",ani:"slash1",com:"攻撃成功時武具を使用していた場合ダメージ分のGを奪う"});
	d.push({id:"C317",type:"C",name:"ノーチラス",		cost:50, color:3,st:40,lf:30,opt1:"@STPLUS@:10!CURSED",opt2:"@LFPLUS@:10!CURSED",img:"nautilus.png",ani:"ball",com:"戦闘時ＳＴ＆ＨＰ＋10[呪いがかかっている領地]"});
	//E
	d.push({id:"C401",type:"C",name:"Ｇ・フロッグ",		cost:60, color:4,st:30,lf:40,opt1:"@POISON@",opt2:"@SHOOT@",img:"gflog",ani:"slash3",com:"猛毒：射撃"});
	d.push({id:"C402",type:"C",name:"ガーゴイル",		cost:70, color:4,st:40,lf:40,walk:"T",opt1:"@DEFBASE@",img:"gargoyle",ani:"slash3",com:"防衛"});
	d.push({id:"C403",type:"C",name:"ケンタウロス",		cost:90, color:4,st:30,lf:30,opt1:"@BAND@",opt2:"@SHOOT@",img:"centaur.png",ani:"slash1",com:"援護：射撃"});
	d.push({id:"C404",type:"C",name:"ロックイーター",	cost:70, color:4,st:30,lf:30,item:"W",opt1:"@LFEQUAL@:TE20",img:"rockeater",ani:"bite",com:"戦闘時ＨＰ＝(所有地属性領地×20)"});
	d.push({id:"C405",type:"C",name:"アース・Ｅ",		cost:60 ,plus:"E",color:4,st:0, lf:20,item:"W",walk:"T",opt1:"@MAPTERRITORYLOCK@",img:"elementale.png",ani:"ball",com:"結界(領地移動不可)"});
	d.push({id:"C406",type:"C",name:"サスカッチ",		cost:110,color:4,st:60,lf:60,item:"WI",img:"fgiant",ani:"slash3"});
	d.push({id:"C407",type:"C",name:"ストーンウォール",	cost:60, color:4,st:0,lf:50,item:"W",walk:"TI",opt1:"@WALL@",img:"walle",ani:"ball",com:"拠点"});
	d.push({id:"C408",type:"C",name:"ドリアード",		cost:80, color:4,st:20,lf:30,item:"W",opt1:"@BAND@",opt2:"@PROTECT@",img:"driard.png",ani:"slash3",com:"援護：保護"});
	d.push({id:"C409",type:"C",name:"バジリスク",		cost:70, color:4,st:40,lf:40,opt1:"@DEATH@",img:"basilisk.png",ani:"bite",com:"即死(アイテム不使用時に相手が使用時)"});
	d.push({id:"C410",type:"C",name:"ドルイド",			cost:70, color:4,st:30,lf:30,opt1:"@RUST@=60",img:"druid.png",ani:"ball",com:"◆破砕(60G)相手プレイヤー全員の手札からアイテム[武具]をランダムに1枚破壊する"});
	d.push({id:"C411",type:"C",name:"エルフレンジャー",	cost:60, color:4,st:30,lf:30,opt1:"@SCOUT@",opt2:"@SPY@",img:"elvenranger.png",ani:"slash1",com:"察知：◇偵察(所有者通過時呪い状態でなければ「啓示」呪い(1ターン)となる)"});
	d.push({id:"C412",type:"C",name:"カーバンクル",		cost:70, color:4,st:20,lf:20,opt1:"@BAND@",opt2:"@REFLECT@",img:"carbuncle.png",ani:"slash3",com:"援護：反射"});
	d.push({id:"C413",type:"C",name:"フォレストマザー",	cost:100,plus:"E",color:4,st:20,lf:40,walk:"TI",opt1:"@LFPLUS@:20!TEE",opt2:"@WALL@",opt3:"@PHANTASM@",img:"fmother.png",ani:"ball",com:"戦闘時ＨＰ＋20[地領地]：拠点：幻影(マップＨＰ固定)"});
	d.push({id:"C414",type:"C",name:"タイタン",			cost:100,plus:"E",color:4,st:50,lf:50,opt1:"@SMASH@!LF50",img:"titan.png",ani:"ball",com:"強打[MAXHP50以上]"});
	d.push({id:"C415",type:"C",name:"ファンガス",		cost:70, color:4,st:20,lf:30,opt1:"@POISON@",opt2:"@DIVISION@=40",img:"fangus.png",ani:"ball",com:"猛毒：◆分裂(40G)"});
	d.push({id:"C416",type:"C",name:"エルフメイジ",		cost:60, plus:"E",color:4,st:30,lf:30,opt1:"@ADAPTATION@",img:"elvenlord.png",ani:"ball",com:"戦闘開始時条件を満たした分だけ能力を付加、先制[戦闘領地が地属性]、呪術[支配領地に隣接]、頑健[城砦に隣接]"});
	d.push({id:"C417",type:"C",name:"マスターパンダ",	cost:60, color:4,st:30,lf:40,item:"I",opt1:"@COUNTER@",img:"masterpanda.png",ani:"ball",com:"戦闘時攻撃ダメージを受けた後にＨＰが1以上あれば受けたダメージを相手に与える"});
	//D
	d.push({id:"C501",type:"C",name:"グリフォン",		cost:90, color:5,st:40,lf:30,opt1:"@FLYING@",img:"gliffin",ani:"slash3",com:"飛行"});
	d.push({id:"C502",type:"C",name:"ペガサス",			cost:80, color:5,st:30,lf:20,opt1:"@FLYING@",opt2:"@GLIDE@=60",img:"pegasus",ani:"slash3",com:"飛行：◆滑空(60G)対象のレベル１の土地に移動"});
	d.push({id:"C503",type:"C",name:"ナイト",			cost:70, color:5,st:40,lf:40,opt1:"@WEAPON@",img:"knight.png",ani:"slash1",com:"強打[武具使用時]"});
	d.push({id:"C504",type:"C",name:"スフィンクス",		cost:70, color:5,st:20,lf:50,opt1:"@FIRST@",opt2:"@SPHINX@",img:"sphinx",ani:"slash3",com:"先制：戦闘時ラウンド数が奇数ならＳＴ＋30＆ＨＰ－30、10の倍数ならＳＴ＋30"});
	d.push({id:"C505",type:"C",name:"サンドゴーレム",	cost:80, color:5,st:60,lf:60,opt1:"@LFPLUS@:RDEC",opt2:"@STPLUS@:RDEC",img:"sgolem",ani:"slash3",com:"戦闘時ＳＴ＆ＨＰ－(ラウンド数)"});
	d.push({id:"C506",type:"C",name:"エア・Ｅ",			cost:60, plus:"D", color:5,st:0, lf:20,item:"W",walk:"T",opt1:"@MAPBTFLYING@",img:"elementala.png",ani:"ball",com:"結界(戦闘時飛行はＳＴ＆ＨＰ＋10)"});
	d.push({id:"C507",type:"C",name:"ウィッチ",			cost:60, color:5,st:0,lf:30,item:"W",opt1:"@CURSEDMG@:30",opt2:"@DRAIN@=30",img:"witch",ani:"ball",com:"呪術(戦闘終了時相手に30ダメージ)：◆吸収(30G)対象プレイヤーの所持魔力の20%を奪う"});
	d.push({id:"C508",type:"C",name:"サンドウォール",	cost:60, color:5,st:0,lf:50,item:"W",walk:"TI",opt1:"@WALL@",img:"walld",ani:"ball",com:"拠点"});
	d.push({id:"C509",type:"C",name:"アークエンジェル",	cost:110,plus:"D",color:5,st:40,lf:40,item:"W",opt1:"@FLYING@",opt2:"@CLEAR@",opt3:"@REMOVE@=40",img:"archangelus.png",ani:"ball",com:"飛行：浄化：◆解呪(40G)対象領地の呪いを解除する"});
	d.push({id:"C510",type:"C",name:"ナイトメア",		cost:60, color:5,st:30,lf:30,opt1:"@NIGHTMARE@",img:"nightmare.png",ani:"ball",com:"周回ボーナス時ラウンド数をチェックする(奇数)ＳＴ＆ＨＰ＋10(最大70)：(偶数)隣接する空き地全てに自身をコピーする"});
	d.push({id:"C511",type:"C",name:"ハーピー",			cost:80, color:5,st:20,lf:30,walk:"E",opt1:"@FLYING@",opt2:"@BIND@",img:"harpy.png",ani:"slash3",com:"飛行：麻痺"});
	d.push({id:"C512",type:"C",name:"キュウビ",			cost:70, plus:"D",color:5,st:30,lf:40,walk:"TI",opt1:"@WALL@",opt2:"@PROTECT@",img:"ninetail.png",ani:"slash3",com:"拠点：保護"});
	d.push({id:"C513",type:"C",name:"グレムリン",		cost:60, color:5,st:30,lf:40,opt1:"@DISCARD@",img:"gremlin.png",ani:"slash3",com:"戦闘時攻撃成功した場合(ダメージが1以上)相手プレイヤーはランダムに手札を1枚破棄"});
	d.push({id:"C514",type:"C",name:"スカウトビー",		cost:70, color:5,st:20,lf:20,opt1:"@FLYING@",opt2:"@SPY@",opt3:"@TOUR@=20",img:"scoutbee.png",ani:"slash3",com:"飛行：察知：◆巡回(20G)対象の風属性土地(空地)に移動"});
	d.push({id:"C515",type:"C",name:"デュラハン",		cost:70, plus:"D",color:5,st:0,lf:40,opt1:"@STEQUAL@:CN10",opt2:"@LFEQUAL@:CN10",img:"dullahan.png",ani:"slash1",com:"戦闘時ＳＴ＆ＨＰ＝(マップ上の無属性クリーチャー×10)"});
	d.push({id:"C516",type:"C",name:"ウロボロス",		cost:90, color:5,st:40,lf:30,item:"I",opt1:"@UROBOROS@",img:"uroboros.png",ani:"bite",com:"戦闘破壊時領地数が最低の場合再召喚される"});
	d.push({id:"C517",type:"C",name:"ムシュフシュ",		cost:80, color:5,st:40,lf:40,walk:"E",opt1:"@POISON@", opt2:"@DIRECT@!POISON",img:"musus.png",ani:"bite",com:"猛毒：貫通[猛毒呪い]"});
	//ITEM
	d.push({id:"I001",type:"I",name:"ロングソード",		cost:40,item:"W",opt1:"STPLUS:40",img:"longsword",com:"ＳＴを40上昇させる"});
	d.push({id:"I002",type:"I",name:"プレートメイル",	cost:40,item:"W",opt1:"LFPLUS:40",img:"platemail",com:"ＨＰを40上昇させる"});
	d.push({id:"I003",type:"I",name:"ロングボウ",		cost:60,item:"W",opt1:"STPLUS:20",opt2:"FIRST",opt3:"SHOOT",img:"longbow.png",com:"ＳＴを20上昇させる：先制：射撃"});
	d.push({id:"I004",type:"I",name:"スレッジハンマー",	cost:60,item:"W",opt1:"STPLUS:30",opt2:"SMASH",opt3:"SLOW",img:"sledge.png",com:"ＳＴを30上昇させる：強打：後手"});
	d.push({id:"I005",type:"I",name:"アイアンハート",	cost:70,item:"I",opt1:"IRONHEART",img:"ironheart.png",com:"ＨＰを超えるダメージを受けた場合、ＨＰ＝1[はじめからＨＰ＝1の時は軽減できない]"});
	d.push({id:"I006",type:"I",name:"ホーリーストーン",	cost:100,item:"I",opt1:"HOLYSTONE",img:"holystone",com:"戦闘開始時相手の援護クリーチャー・アイテムカードを破壊する"});
	d.push({id:"I007",type:"I",name:"アサシンクローク",	cost:40,item:"I",opt1:"STPLUS:40!NOITEM",opt2:"LFPLUS:40!NOITEM",img:"assassin",com:"相手がアイテムカード未使用時、ＳＴ＆ＨＰを40上昇させる"});
	d.push({id:"I008",type:"I",name:"イビルストーン",	cost:60,item:"I",opt1:"EVILSTONE",img:"evilstone",com:"戦闘時相手クリーチャーの能力が発生しなくなる"});
	d.push({id:"I009",type:"I",name:"ディバイン・Ｓ",	cost:60,item:"I",opt1:"DIVINESTONE",img:"divinestone",com:"ダメージを1/2跳ね返す"});
	d.push({id:"I010",type:"I",name:"バックラー",		cost:40,item:"W",opt1:"LFPLUS:20",opt2:"STMINUS:20",opt3:"BACKHAND",img:"buckler.png",com:"ＳＴ－20：ＨＰ＋20：手札復帰"});
	d.push({id:"I011",type:"I",name:"スピア",			cost:60,item:"W",opt1:"LFPLUS:20",opt2:"STPLUS:20",opt3:"SHOOT",img:"spear.png",com:"ＳＴ＋20：ＨＰ＋20：射撃"});
	d.push({id:"I012",type:"I",name:"コールドストーン",	cost:40,item:"I",opt1:"STEQUAL:50",opt2:"LFEQUAL:50",img:"coldstone.png",com:"ＳＴ＝50：ＨＰ＝50"});
	d.push({id:"I013",type:"I",name:"フェザークラウン",	cost:40,item:"I",opt1:"FIRST",opt2:"BACKHAND",img:"feathercrown.png",com:"先制：手札復帰"});
	d.push({id:"I014",type:"I",name:"オオダチ",			cost:80,item:"W",opt1:"STPLUS:HANDM80",img:"ootachi.png",com:"ＳＴ＋80－(自分の手札枚数×10)"});
	d.push({id:"I015",type:"I",name:"ブラックスワン",	cost:0, item:"I",opt1:"BLACKSWAN",img:"blackswan.png",com:"戦闘終了時対戦相手が生存していればHP×10Gを得る"});
	d.push({id:"I016",type:"I",name:"レイピア",			cost:30,item:"W",opt1:"STPLUS:30",opt2:"REVDEATH",img:"rapier.png",com:"ＳＴを30上昇させる：雪辱[即死]"});
	d.push({id:"I017",type:"I",name:"イージス",			cost:60,item:"W",opt1:"LFPLUS:20",opt2:"AEGIS",img:"aegis.png",com:"ＨＰ＋20：無効[相手が武具使用時]"});
	//SPELL
	d.push({id:"S001",type:"S",name:"マナ",				cost:0,  spell:"MANA",		tgt:"AMP",img:"mana",com:"周回数×50Gを得る"});
	d.push({id:"S002",type:"S",name:"ドゥームダイス１",	cost:30, spell:"SETSTATUSP",tgt:"TEP",opt1:"_DICE_:1",opt2:1,img:"magicdice1.png",com:"(呪い1ターン)対象プレイヤーのダイスは1になる"});
	d.push({id:"S003",type:"S",name:"ドゥームダイス７",	cost:60, spell:"SETSTATUSP",tgt:"TEP",opt1:"_DICE_:7",opt2:1,img:"magicdice7.png",com:"(呪い1ターン)対象プレイヤーのダイスは7になる"});
	d.push({id:"S004",type:"S",name:"ホープ",			cost:40, spell:"DRAW",		tgt:"AMP",opt1:2,img:"hope",com:"カードを2枚引く"});
	d.push({id:"S005",type:"S",name:"ヒール",			cost:30, spell:"HEAL",		tgt:"TEGALL",img:"heal",com:"対象クリーチャーのHPを全回復し、全ての呪いを解除する：デッキ復帰"});
	d.push({id:"S006",type:"S",name:"シャッター",		cost:60, spell:"SHUTTER",	tgt:"TOP",img:"shatter.png",com:"対象プレイヤーのアイテムカード、スペルカードの内1枚を選択して破壊する"});
	d.push({id:"S007",type:"S",name:"アップヒーバル",	cost:150,spell:"COLORCHANGE",tgt:"TEG",opt1:2,img:"colorf",com:"対象の領地を火属性に変える"});
	d.push({id:"S008",type:"S",name:"シンク",			cost:150,spell:"COLORCHANGE",tgt:"TEG",opt1:3,img:"colorw",com:"対象の領地を水属性に変える"});
	d.push({id:"S009",type:"S",name:"ワイルドグロース",	cost:150,spell:"COLORCHANGE",tgt:"TEG",opt1:4,img:"colore",com:"対象の領地を地属性に変える"});
	d.push({id:"S010",type:"S",name:"ウェザリング",		cost:150,spell:"COLORCHANGE",tgt:"TEG",opt1:5,img:"colord",com:"対象の領地を風属性に変える"});
	d.push({id:"S011",type:"S",name:"リンカネーション",	cost:40, spell:"REINCARNE"	,tgt:"AMP",img:"reincarne",com:"手札を全て破棄して、破棄枚数+1枚を引く"});
	d.push({id:"S012",type:"S",name:"マジックボルト",	cost:60, spell:"DAMAGE",	tgt:"TOG",opt1:20,img:"magicbolt",com:"対象クリーチャーに20ダメージ"});
	d.push({id:"S013",type:"S",name:"バンク",			cost:0,  spell:"SETSTATUSP",tgt:"AMP",opt1:"_BANK_:250", opt2:2, img:"bank",com:"(呪い2ターン)2ターン後に250Gを得る"});
	d.push({id:"S014",type:"S",name:"インスペクション",	cost:40, spell:"INSPECTION",tgt:"AOP",img:"inspection",com:"相手全員からアイテムカード枚数×30Gを奪う(可能なかぎり)"});
	d.push({id:"S015",type:"S",name:"マーケット",		cost:40, spell:"MARKET",	tgt:"AOP",img:"market",com:"相手全員の手札からスペルカードを各2枚ランダムに表示し、選択したカードを取得して所有者に80G支払う"});
	d.push({id:"S016",type:"S",name:"ドレインマジック",	cost:80, spell:"DRAIN",		tgt:"TOP",opt1:30,img:"drain",com:"対象プレイヤーの所持魔力の30%を奪う"});
	d.push({id:"S017",type:"S",name:"テレポート",		cost:40, spell:"TELEPORT",	tgt:"AMP",opt1:"special",img:"teleport",com:"一番近い特殊地形に移動する(複数存在する場合は選択)(ダイス使用不可)"});
	d.push({id:"S018",type:"S",name:"バインド",			cost:60, spell:"SETSTATUSG",tgt:"TEG",opt1:"_BIND_",opt2:99,img:"bind",com:"(呪い)対象のクリーチャーは「麻痺」呪いとなる"});
	d.push({id:"S019",type:"S",name:"フリング",			cost:50, spell:"FLING",		tgt:"TSG",img:"fling",com:"使用者が支配領地上にいる場合、配置クリーチャーを対象の空き土地に移動する：デッキ復帰"});
	d.push({id:"S020",type:"S",name:"フォージリィ",		cost:80, spell:"SETSTATUSP",tgt:"AMP",opt1:"_FORGERY_",opt2:99,img:"forgery",com:"(呪い城まで)通過砦に関わらず城到着にて周回となる：基礎ボーナス×1.5：砦ボーナスが受け取れない"});
	d.push({id:"S021",type:"S",name:"プロテクト",		cost:70, spell:"SETSTATUSG",tgt:"TEG",opt1:"_PROTECT_",opt2:99,img:"protect.png",com:"(呪い)対象の領地はスペル、領地能力の対象に選択できない"});
	d.push({id:"S022",type:"S",name:"アンサモン",		cost:140,spell:"UNSUMMON",	tgt:"TOG",img:"unsummon",com:"対象のダメージを受けているクリーチャーを使用者の手札に戻す"});
	d.push({id:"S023",type:"S",name:"ナビゲート",		cost:50, spell:"SETSTATUSP",tgt:"AMP",opt1:"_NAVIGATE_",opt2:2,img:"navigate",com:"(呪い2ターン)ダイスの結果を二つから選択できる"});
	d.push({id:"S024",type:"S",name:"ディザスター",		cost:200,spell:"AREADMG",	tgt:"AEGMASS",opt1:20,img:"dizaster",com:"マップ上に最も多い属性土地にいるクリーチャー全てに20ダメージ"});
	d.push({id:"S025",type:"S",name:"リコンストラクト",	cost:80 ,spell:"SETSTATUSG",tgt:"TEG",opt1:"_RECONSTRUCT_",opt2:99,opt3:"draw",img:"reconstruct",com:"(呪い)対象領地上でターン終了された場合、基本土地価値が10上昇(最大200)：カードを１枚引く"});
	d.push({id:"S026",type:"S",name:"フェスティバル",	cost:0,  spell:"FESTIVAL",	tgt:"AMP",opt1:150,img:"festival.png",com:"使用者は手札のクリーチャーカードを全て破棄し、破棄枚数×150Gを得る"});
	d.push({id:"S027",type:"S",name:"テレグノーシス",	cost:70, spell:"SETSTATUSP",tgt:"AMP",opt1:"_TELEGNOSIS_", opt2:2, img:"telegnosis",com:"(呪い2ターン)領地コマンド時全ての自領地を選択できる"});
	d.push({id:"S028",type:"S",name:"アースクエイク",	cost:250,spell:"EARTHQUAKE",tgt:"AEGGRD",img:"earthquake",com:"手札から「アースクエイク」を全て破棄：飛行を持たないクリーチャー全てに10＋(破棄枚数×10)ダメージ(最大30)"});
	d.push({id:"S029",type:"S",name:"フォーサイト",		cost:40, spell:"FORESIGHT",	tgt:"AMP",opt1:4,img:"foresight",com:"デッキの上から4枚確認して選択した1枚を引く(デッキの残り枚数以上は確認できない)"});
	d.push({id:"S030",type:"S",name:"ショートカット",	cost:30, spell:"SETSTATUSP",tgt:"AMP",opt1:"_SHORTCUT_:3",opt2:3,img:"shortcut",com:"(呪い3ターン)ダイスの最大値をマップの最大値＋3"});
	d.push({id:"S031",type:"S",name:"ジェイル",			cost:80, spell:"SETSTATUSG",tgt:"TEG",opt1:"_JAIL_",opt2:99,img:"jail",com:"(呪い)対象の領地は戦闘不可となり通行料が発生しない：領地コマンド「レベルアップ」「地形変化」が行えない"});
	d.push({id:"S032",type:"S",name:"プレイグ",			cost:70, spell:"SETSTATUSP",tgt:"TEP",opt1:"_PLAGUE_",opt2:2,img:"plague",com:"(呪い2ターン)対象プレイヤーは「疫病」呪いとなる(疫病呪いのプレイヤーが通過した領地は「猛毒」呪いとなる)"});
	d.push({id:"S033",type:"S",name:"フラットライン",	cost:60, spell:"FLATLINE",	tgt:"AEP",img:"flatline",com:"プレイヤー全員の手札は4枚となるようにデッキからドローまたは手札がランダム破棄される。"});
	d.push({id:"S034",type:"S",name:"エクスチェンジ",	cost:30, spell:"EXCHANGE",	tgt:"TMG,TOG",img:"exchange.png",com:"対象の支配クリーチャー1体と対象の相手クリーチャー１体のＳＴを入れ替える：デッキ復帰"});
	d.push({id:"S035",type:"S",name:"バリアー",			cost:60, spell:"SETSTATUSP",tgt:"AMP",opt1:"_BARRIER_",opt2:6,img:"barrier.png",com:"(呪い4ターン)使用者は対象を取るスペル・領地能力の対象にならない"});
	d.push({id:"S036",type:"S",name:"リリーフ",			cost:30, spell:"RELIEF",	tgt:"TMG,TMG",img:"relief.png",com:"対象の支配クリーチャーを2体選択し位置を入れ替える：デッキ復帰"});
	d.push({id:"S037",type:"S",name:"インシネレイト",	cost:70, spell:"INCINERATE",tgt:"TOG",opt1:10,img:"incinerate.png",com:"対象クリーチャーに10＋(既に使用された「インシネレイト」の枚数×10)ダメージ(最大40)"});
	d.push({id:"S038",type:"S",name:"コンプレッション",	cost:40, spell:"COMPRESSION",tgt:"TEP",img:"compression.png",com:"対象プレイヤーのデッキの上から5枚確認して選択したカードまで上から破棄する。"});
	d.push({id:"S039",type:"S",name:"コントラクト",		cost:120,spell:"CONTRACT",	tgt:"TEG",img:"contract.png",com:"MHP－20：(呪い)通行料が所有者の最大通行料と同額となる"});
	d.push({id:"S040",type:"S",name:"パニッシャー",		cost:150,spell:"AREADMG",	tgt:"AEGCURSED",opt1:20,img:"panisher.png",com:"呪い状態のクリーチャー全てに20ダメージ"});
	d.push({id:"S041",type:"S",name:"テレパシー",		cost:50, spell:"SETSTATUSG",tgt:"TEG",opt1:"_TELEPATHY_",opt2:99,img:"telepathy.png",com:"(呪い)常に領地コマンド対象となる：領地コマンド使用時呪い解除"});
	//d.push({id:"S042",type:"S",name:"リンクゲート",		cost:60, spell:"LINKGATE",	tgt:"AMG",opt1:"_LINKGATE_",opt2:99,img:"linkgate.png",com:"(呪い)対象の属性色の支配領地は転送呪い(この領地に停止時支配領地なら他の転送呪いに移動可)となる"});
	d.push({id:"S043",type:"S",name:"バランス",			cost:30, spell:"BALANCE",	tgt:"AEP",img:"balance.png",com:"全てのプレイヤーは順位×領地数×20Gを得る"});
	d.push({id:"S044",type:"S",name:"グラビティ",		cost:70, spell:"SETSTATUSG",tgt:"TEG",opt1:"_GRAVITY_",opt2:99,opt3:"draw",img:"gravity.png",com:"(呪い)対象のクリーチャーは「重力」呪い(領地移動不可：戦闘時ＳＴ－10、ＨＰ＋10)となる：カードを1枚引く"});
	d.push({id:"S045",type:"S",name:"オブリビオン",		cost:40, spell:"SETSTATUSG",tgt:"TEG",opt1:"_FORGET_",opt2:99,img:"oblivion.png",com:"(呪い)対象のクリーチャーは「忘却」呪いとなる"});
	d.push({id:"S046",type:"S",name:"フラクチャー",		cost:150,spell:"FRACTURE",	tgt:"TEG",img:"fracture.png",com:"対象の領地はレベル1にする：その後所有者のランダムな土地1つを下降したレベル分レベル上昇する"});
	d.push({id:"S047",type:"S",name:"エスケープ",		cost:20, spell:"TELEPORT",	tgt:"AMP",opt1:"escape",img:"escape.png",com:"使用者は一番近い空き地に移動する(複数存在する場合は選択)(ダイス使用不可)"});
	d.push({id:"S048",type:"S",name:"ハリケーン",		cost:120,spell:"AREASTATUS",tgt:"AEGFLY",opt1:"_BIND_",opt2:2,img:"hurricane.png",com:"(呪い2ターン)飛行を持つクリーチャーは全て「麻痺」呪いとなる"});
	d.push({id:"S049",type:"S",name:"ウォークライ",		cost:60, spell:"SETSTATUSP",tgt:"AMP",opt1:"_WARCRY_",opt2:99,img:"warcry.png",com:"(呪い)使用者は「行軍」呪いとなる(ターン開始時のドローカードを公開：クリーチャーだった場合コスト分のＧを得る)"});
	d.push({id:"S050",type:"S",name:"ソウルコレクト",	cost:10, spell:"SOULCOLECT",tgt:"AMP",opt1:40,img:"soulcolect.png",com:"破壊クリーチャー数×40Gを得る：破壊クリーチャー数は0となる"});
	d.push({id:"S051",type:"S",name:"ギャザー",			cost:0,  spell:"SETSTATUSP",tgt:"AMP",opt1:"_GATHER_",opt2:3,img:"gather.png",com:"(呪い3ターン)対象プレイヤーは「収集」呪いとなる"});
	d.push({id:"S052",type:"S",name:"ルイン",			cost:100,spell:"RUIN",		tgt:"AEP",img:"ruin.png",com:"プレイヤー全員の手札にあるアイテムカード[道具]を破壊する"});
	d.push({id:"S053",type:"S",name:"スワンプ",			cost:120,spell:"SETSTATUSG",tgt:"TEG",opt1:"_SWAMP_",opt2:4,img:"swamp.png",com:"(呪い4ターン)対象領地の地価は70%となる"});
	d.push({id:"S054",type:"S",name:"インフルエンス",	cost:80, spell:"INFLUENCE",	tgt:"TEG",img:"influence.png",com:"対象の領地を所有者が最も所持している属性に変える"});
	d.push({id:"S055",type:"S",name:"ディストーション",	cost:70, spell:"DISTORTION",tgt:"TEG",img:"distortion.png",com:"対象のクリーチャーはデッキ内のランダムなクリーチャーと交換される"});
	d.push({id:"S056",type:"S",name:"モノポリー",		cost:120,spell:"MONOPOLY",	tgt:"AMP",opt1:"_MONOPOLY_",opt2:1,img:"monopoly.png",com:"(呪い1ターン)使用者は「独占」呪いとなる(通行料を全て奪う)：他のプレイヤー「独占」呪いを解除"});
	d.push({id:"S057",type:"S",name:"スピリットウォーク",cost:20, spell:"SETSTATUSG",tgt:"TEG",opt1:"_SPIRITWALK_",opt2:99,img:"spiritwalk.png",com:"(呪い)対象のクリーチャーは「跳躍」呪いとなる"});
	d.push({id:"S058",type:"S",name:"リサーチ",			cost:40, spell:"DRAW",		tgt:"AMP",opt1:1,opt2:"hand",img:"research.png",com:"カードを1枚引く：手札復帰"});
	d.push({id:"S059",type:"S",name:"クエスト",			cost:20, spell:"QUEST",		tgt:"AMP",opt1:"_QUEST_",opt2:3,img:"quest.png",com:"(呪い3ターン)使用者は「冒険」呪いとなる(侵略成功時呪い以降の侵略成功回数×200Gを得て期間が再び3ターンとなる：最大3回)"});
	d.push({id:"S060",type:"S",name:"アップドラフト",	cost:80, spell:"AREASTATUS",tgt:"AEGHP30",opt1:"_SPIRITWALK_",img:"updraft.png",com:"(呪い)ＭＨＰが30以下のクリーチャーは「跳躍」呪いとなる"});
	d.push({id:"S061",type:"S",name:"プライア",			cost:60, spell:"SETSTATUSP",tgt:"AMP",opt1:"_PRAYER_",opt2:1,img:"testspell",com:"(呪い1ターン)使用者は「祈願」呪いとなる(土地レベルアップコストが1/2となる)"});
	//返却値
	return d;
}
