var d = new Date().getTime();
document.write('<script type="text/javascript" src="js/index.js?'+d+'"></script>');
document.write('<script type="text/javascript" src="js/deckedit.js?'+d+'"></script>');
document.write('<script type="text/javascript" src="js/class.js?'+d+'"></script>');
document.write('<script type="text/javascript" src="js/var.js?'+d+'"></script>');
document.write('<script type="text/javascript" src="js/canvas2.js?'+d+'"></script>');
document.write('<script type="text/javascript" src="js/data_card.js?'+d+'"></script>');
document.write('<script type="text/javascript" src="js/data_map.js?'+d+'"></script>');
document.write('<script type="text/javascript" src="js/data_ability.js?'+d+'"></script>');
document.write('<script type="text/javascript" src="js/dictionary.js?'+d+'"></script>');
document.write('<script type="text/javascript" src="js/tool.js?'+d+'"></script>');
document.write('<script type="text/javascript" src="js/infoblock.js?'+d+'"></script>');
document.write('<script type="text/javascript" src="js/lobbychat.js?'+d+'"></script>');