var d = new Date().getTime();
document.write('<script type="text/javascript" src="jsindex/index.js?'+d+'"></script>');
document.write('<script type="text/javascript" src="jsindex/deckedit.js?'+d+'"></script>');
document.write('<script type="text/javascript" src="jstool/canvas.js?'+d+'"></script>');
document.write('<script type="text/javascript" src="jsdata/data_card.js?'+d+'"></script>');
document.write('<script type="text/javascript" src="jsdata/data_map.js?'+d+'"></script>');
document.write('<script type="text/javascript" src="jsdata/data_ability.js?'+d+'"></script>');
document.write('<script type="text/javascript" src="jsdata/dictionary.js?'+d+'"></script>');
document.write('<script type="text/javascript" src="jstool/tool.js?'+d+'"></script>');
document.write('<script type="text/javascript" src="js/infoblock.js?'+d+'"></script>');